// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: docpb/datastore.proto

package docpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_docpb_datastore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateDocumentRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDocumentRequest) Reset() {
	*x = SetDocumentRequest{}
	mi := &file_docpb_datastore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDocumentRequest) ProtoMessage() {}

func (x *SetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDocumentRequest.ProtoReflect.Descriptor instead.
func (*SetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{1}
}

func (x *SetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetDocumentRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateDocumentRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Id            string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Updates       []*UpdateDocumentRequest_Field `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	Preconditions []*UpdateDocumentRequest_Field `protobuf:"bytes,3,rep,name=preconditions,proto3" json:"preconditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_docpb_datastore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDocumentRequest) GetUpdates() []*UpdateDocumentRequest_Field {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *UpdateDocumentRequest) GetPreconditions() []*UpdateDocumentRequest_Field {
	if x != nil {
		return x.Preconditions
	}
	return nil
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_docpb_datastore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_docpb_datastore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDocumentRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Filters       []*ListDocumentRequest_Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentRequest) Reset() {
	*x = ListDocumentRequest{}
	mi := &file_docpb_datastore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentRequest) ProtoMessage() {}

func (x *ListDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentRequest) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{5}
}

func (x *ListDocumentRequest) GetFilters() []*ListDocumentRequest_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type DocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentResponse) Reset() {
	*x = DocumentResponse{}
	mi := &file_docpb_datastore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResponse) ProtoMessage() {}

func (x *DocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResponse.ProtoReflect.Descriptor instead.
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{6}
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	NotFound      bool                   `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_docpb_datastore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{7}
}

func (x *GetDocumentResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetDocumentResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

type ListDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentResponse) Reset() {
	*x = ListDocumentResponse{}
	mi := &file_docpb_datastore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentResponse) ProtoMessage() {}

func (x *ListDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentResponse) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{8}
}

func (x *ListDocumentResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListDocumentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlreadyExists bool                   `protobuf:"varint,1,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentResponse) Reset() {
	*x = CreateDocumentResponse{}
	mi := &file_docpb_datastore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentResponse) ProtoMessage() {}

func (x *CreateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentResponse.ProtoReflect.Descriptor instead.
func (*CreateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{9}
}

func (x *CreateDocumentResponse) GetAlreadyExists() bool {
	if x != nil {
		return x.AlreadyExists
	}
	return false
}

type UpdateDocumentResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NotFound           bool                   `protobuf:"varint,1,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	PreconditionFailed bool                   `protobuf:"varint,2,opt,name=precondition_failed,json=preconditionFailed,proto3" json:"precondition_failed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateDocumentResponse) Reset() {
	*x = UpdateDocumentResponse{}
	mi := &file_docpb_datastore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentResponse) ProtoMessage() {}

func (x *UpdateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateDocumentResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

func (x *UpdateDocumentResponse) GetPreconditionFailed() bool {
	if x != nil {
		return x.PreconditionFailed
	}
	return false
}

type UpdateDocumentRequest_Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldPath     []string               `protobuf:"bytes,1,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest_Field) Reset() {
	*x = UpdateDocumentRequest_Field{}
	mi := &file_docpb_datastore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest_Field) ProtoMessage() {}

func (x *UpdateDocumentRequest_Field) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest_Field.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest_Field) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UpdateDocumentRequest_Field) GetFieldPath() []string {
	if x != nil {
		return x.FieldPath
	}
	return nil
}

func (x *UpdateDocumentRequest_Field) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListDocumentRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldPath     []string               `protobuf:"bytes,1,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentRequest_Filter) Reset() {
	*x = ListDocumentRequest_Filter{}
	mi := &file_docpb_datastore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentRequest_Filter) ProtoMessage() {}

func (x *ListDocumentRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_docpb_datastore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListDocumentRequest_Filter) Descriptor() ([]byte, []int) {
	return file_docpb_datastore_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListDocumentRequest_Filter) GetFieldPath() []string {
	if x != nil {
		return x.FieldPath
	}
	return nil
}

func (x *ListDocumentRequest_Filter) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListDocumentRequest_Filter) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

var File_docpb_datastore_proto protoreflect.FileDescriptor

const file_docpb_datastore_proto_rawDesc = "" +
	"\n" +
	"\x15docpb/datastore.proto\x12\x05proto\";\n" +
	"\x15CreateDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"8\n" +
	"\x12SetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xeb\x01\n" +
	"\x15UpdateDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\aupdates\x18\x02 \x03(\v2\".proto.UpdateDocumentRequest.FieldR\aupdates\x12H\n" +
	"\rpreconditions\x18\x03 \x03(\v2\".proto.UpdateDocumentRequest.FieldR\rpreconditions\x1a:\n" +
	"\x05Field\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x03(\tR\tfieldPath\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15DeleteDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xad\x01\n" +
	"\x13ListDocumentRequest\x12;\n" +
	"\afilters\x18\x01 \x03(\v2!.proto.ListDocumentRequest.FilterR\afilters\x1aY\n" +
	"\x06Filter\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x03(\tR\tfieldPath\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\"\x12\n" +
	"\x10DocumentResponse\"F\n" +
	"\x13GetDocumentResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tnot_found\x18\x02 \x01(\bR\bnotFound\"@\n" +
	"\x14ListDocumentResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"?\n" +
	"\x16CreateDocumentResponse\x12%\n" +
	"\x0ealready_exists\x18\x01 \x01(\bR\ralreadyExists\"f\n" +
	"\x16UpdateDocumentResponse\x12\x1b\n" +
	"\tnot_found\x18\x01 \x01(\bR\bnotFound\x12/\n" +
	"\x13precondition_failed\x18\x02 \x01(\bR\x12preconditionFailed2\x9a\x03\n" +
	"\rDocumentStore\x12E\n" +
	"\x06Create\x12\x1c.proto.CreateDocumentRequest\x1a\x1d.proto.CreateDocumentResponse\x129\n" +
	"\x03Set\x12\x19.proto.SetDocumentRequest\x1a\x17.proto.DocumentResponse\x12E\n" +
	"\x06Update\x12\x1c.proto.UpdateDocumentRequest\x1a\x1d.proto.UpdateDocumentResponse\x12<\n" +
	"\x03Get\x12\x19.proto.GetDocumentRequest\x1a\x1a.proto.GetDocumentResponse\x12?\n" +
	"\x06Delete\x12\x1c.proto.DeleteDocumentRequest\x1a\x17.proto.DocumentResponse\x12A\n" +
	"\x04List\x12\x1a.proto.ListDocumentRequest\x1a\x1b.proto.ListDocumentResponse0\x01B\bZ\x06/docpbb\x06proto3"

var (
	file_docpb_datastore_proto_rawDescOnce sync.Once
	file_docpb_datastore_proto_rawDescData []byte
)

func file_docpb_datastore_proto_rawDescGZIP() []byte {
	file_docpb_datastore_proto_rawDescOnce.Do(func() {
		file_docpb_datastore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docpb_datastore_proto_rawDesc), len(file_docpb_datastore_proto_rawDesc)))
	})
	return file_docpb_datastore_proto_rawDescData
}

var file_docpb_datastore_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_docpb_datastore_proto_goTypes = []any{
	(*CreateDocumentRequest)(nil),       // 0: proto.CreateDocumentRequest
	(*SetDocumentRequest)(nil),          // 1: proto.SetDocumentRequest
	(*UpdateDocumentRequest)(nil),       // 2: proto.UpdateDocumentRequest
	(*GetDocumentRequest)(nil),          // 3: proto.GetDocumentRequest
	(*DeleteDocumentRequest)(nil),       // 4: proto.DeleteDocumentRequest
	(*ListDocumentRequest)(nil),         // 5: proto.ListDocumentRequest
	(*DocumentResponse)(nil),            // 6: proto.DocumentResponse
	(*GetDocumentResponse)(nil),         // 7: proto.GetDocumentResponse
	(*ListDocumentResponse)(nil),        // 8: proto.ListDocumentResponse
	(*CreateDocumentResponse)(nil),      // 9: proto.CreateDocumentResponse
	(*UpdateDocumentResponse)(nil),      // 10: proto.UpdateDocumentResponse
	(*UpdateDocumentRequest_Field)(nil), // 11: proto.UpdateDocumentRequest.Field
	(*ListDocumentRequest_Filter)(nil),  // 12: proto.ListDocumentRequest.Filter
}
var file_docpb_datastore_proto_depIdxs = []int32{
	11, // 0: proto.UpdateDocumentRequest.updates:type_name -> proto.UpdateDocumentRequest.Field
	11, // 1: proto.UpdateDocumentRequest.preconditions:type_name -> proto.UpdateDocumentRequest.Field
	12, // 2: proto.ListDocumentRequest.filters:type_name -> proto.ListDocumentRequest.Filter
	0,  // 3: proto.DocumentStore.Create:input_type -> proto.CreateDocumentRequest
	1,  // 4: proto.DocumentStore.Set:input_type -> proto.SetDocumentRequest
	2,  // 5: proto.DocumentStore.Update:input_type -> proto.UpdateDocumentRequest
	3,  // 6: proto.DocumentStore.Get:input_type -> proto.GetDocumentRequest
	4,  // 7: proto.DocumentStore.Delete:input_type -> proto.DeleteDocumentRequest
	5,  // 8: proto.DocumentStore.List:input_type -> proto.ListDocumentRequest
	9,  // 9: proto.DocumentStore.Create:output_type -> proto.CreateDocumentResponse
	6,  // 10: proto.DocumentStore.Set:output_type -> proto.DocumentResponse
	10, // 11: proto.DocumentStore.Update:output_type -> proto.UpdateDocumentResponse
	7,  // 12: proto.DocumentStore.Get:output_type -> proto.GetDocumentResponse
	6,  // 13: proto.DocumentStore.Delete:output_type -> proto.DocumentResponse
	8,  // 14: proto.DocumentStore.List:output_type -> proto.ListDocumentResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_docpb_datastore_proto_init() }
func file_docpb_datastore_proto_init() {
	if File_docpb_datastore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docpb_datastore_proto_rawDesc), len(file_docpb_datastore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docpb_datastore_proto_goTypes,
		DependencyIndexes: file_docpb_datastore_proto_depIdxs,
		MessageInfos:      file_docpb_datastore_proto_msgTypes,
	}.Build()
	File_docpb_datastore_proto = out.File
	file_docpb_datastore_proto_goTypes = nil
	file_docpb_datastore_proto_depIdxs = nil
}
