// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: docpb/datastore.proto

package docpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentStore_Create_FullMethodName = "/proto.DocumentStore/Create"
	DocumentStore_Set_FullMethodName    = "/proto.DocumentStore/Set"
	DocumentStore_Update_FullMethodName = "/proto.DocumentStore/Update"
	DocumentStore_Get_FullMethodName    = "/proto.DocumentStore/Get"
	DocumentStore_Delete_FullMethodName = "/proto.DocumentStore/Delete"
	DocumentStore_List_FullMethodName   = "/proto.DocumentStore/List"
)

// DocumentStoreClient is the client API for DocumentStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentStoreClient interface {
	Create(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error)
	Set(ctx context.Context, in *SetDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	Update(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error)
	Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	Delete(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	List(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListDocumentResponse], error)
}

type documentStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentStoreClient(cc grpc.ClientConnInterface) DocumentStoreClient {
	return &documentStoreClient{cc}
}

func (c *documentStoreClient) Create(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Set(ctx context.Context, in *SetDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Update(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Delete(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) List(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListDocumentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentStore_ServiceDesc.Streams[0], DocumentStore_List_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListDocumentRequest, ListDocumentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_ListClient = grpc.ServerStreamingClient[ListDocumentResponse]

// DocumentStoreServer is the server API for DocumentStore service.
// All implementations must embed UnimplementedDocumentStoreServer
// for forward compatibility.
type DocumentStoreServer interface {
	Create(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error)
	Set(context.Context, *SetDocumentRequest) (*DocumentResponse, error)
	Update(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error)
	Get(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	Delete(context.Context, *DeleteDocumentRequest) (*DocumentResponse, error)
	List(*ListDocumentRequest, grpc.ServerStreamingServer[ListDocumentResponse]) error
	mustEmbedUnimplementedDocumentStoreServer()
}

// UnimplementedDocumentStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentStoreServer struct{}

func (UnimplementedDocumentStoreServer) Create(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDocumentStoreServer) Set(context.Context, *SetDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedDocumentStoreServer) Update(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDocumentStoreServer) Get(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDocumentStoreServer) Delete(context.Context, *DeleteDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDocumentStoreServer) List(*ListDocumentRequest, grpc.ServerStreamingServer[ListDocumentResponse]) error {
	return status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDocumentStoreServer) mustEmbedUnimplementedDocumentStoreServer() {}
func (UnimplementedDocumentStoreServer) testEmbeddedByValue()                       {}

// UnsafeDocumentStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentStoreServer will
// result in compilation errors.
type UnsafeDocumentStoreServer interface {
	mustEmbedUnimplementedDocumentStoreServer()
}

func RegisterDocumentStoreServer(s grpc.ServiceRegistrar, srv DocumentStoreServer) {
	// If the following call panics, it indicates UnimplementedDocumentStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentStore_ServiceDesc, srv)
}

func _DocumentStore_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Create(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Set(ctx, req.(*SetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Update(ctx, req.(*UpdateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Get(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Delete(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDocumentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentStoreServer).List(m, &grpc.GenericServerStream[ListDocumentRequest, ListDocumentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_ListServer = grpc.ServerStreamingServer[ListDocumentResponse]

// DocumentStore_ServiceDesc is the grpc.ServiceDesc for DocumentStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DocumentStore",
	HandlerType: (*DocumentStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DocumentStore_Create_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _DocumentStore_Set_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DocumentStore_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DocumentStore_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DocumentStore_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _DocumentStore_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "docpb/datastore.proto",
}
