// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: docpb/datastore.proto

package docpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentStore_Create_FullMethodName = "/proto.DocumentStore/Create"
	DocumentStore_Set_FullMethodName    = "/proto.DocumentStore/Set"
	DocumentStore_Update_FullMethodName = "/proto.DocumentStore/Update"
	DocumentStore_Get_FullMethodName    = "/proto.DocumentStore/Get"
	DocumentStore_Delete_FullMethodName = "/proto.DocumentStore/Delete"
	DocumentStore_List_FullMethodName   = "/proto.DocumentStore/List"
)

// DocumentStoreClient is the client API for DocumentStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentStoreClient interface {
	// Create, Set, Update and Get stream their document payload so a single
	// document can exceed the gRPC per-message size limit. The blob is split
	// into chunks; identity/metadata travels on the first stream message only:
	//
	//	Create/Set:  first message carries id; every message carries a data
	//	             chunk. The server concatenates chunks before decoding.
	//	Update:      first message carries id; updates/preconditions are
	//	             streamed across messages and concatenated by field path.
	//	Get:         the response is streamed. The first message may carry
	//	             not_found; otherwise N messages each carry a data chunk
	//	             that the client concatenates before decoding.
	Create(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateDocumentRequest, CreateDocumentResponse], error)
	Set(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SetDocumentRequest, DocumentResponse], error)
	Update(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateDocumentRequest, UpdateDocumentResponse], error)
	Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDocumentResponse], error)
	Delete(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	List(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListDocumentResponse], error)
}

type documentStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentStoreClient(cc grpc.ClientConnInterface) DocumentStoreClient {
	return &documentStoreClient{cc}
}

func (c *documentStoreClient) Create(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateDocumentRequest, CreateDocumentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentStore_ServiceDesc.Streams[0], DocumentStore_Create_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateDocumentRequest, CreateDocumentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_CreateClient = grpc.ClientStreamingClient[CreateDocumentRequest, CreateDocumentResponse]

func (c *documentStoreClient) Set(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SetDocumentRequest, DocumentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentStore_ServiceDesc.Streams[1], DocumentStore_Set_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetDocumentRequest, DocumentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_SetClient = grpc.ClientStreamingClient[SetDocumentRequest, DocumentResponse]

func (c *documentStoreClient) Update(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateDocumentRequest, UpdateDocumentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentStore_ServiceDesc.Streams[2], DocumentStore_Update_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateDocumentRequest, UpdateDocumentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_UpdateClient = grpc.ClientStreamingClient[UpdateDocumentRequest, UpdateDocumentResponse]

func (c *documentStoreClient) Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDocumentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentStore_ServiceDesc.Streams[3], DocumentStore_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDocumentRequest, GetDocumentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_GetClient = grpc.ServerStreamingClient[GetDocumentResponse]

func (c *documentStoreClient) Delete(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, DocumentStore_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) List(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListDocumentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentStore_ServiceDesc.Streams[4], DocumentStore_List_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListDocumentRequest, ListDocumentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_ListClient = grpc.ServerStreamingClient[ListDocumentResponse]

// DocumentStoreServer is the server API for DocumentStore service.
// All implementations must embed UnimplementedDocumentStoreServer
// for forward compatibility.
type DocumentStoreServer interface {
	// Create, Set, Update and Get stream their document payload so a single
	// document can exceed the gRPC per-message size limit. The blob is split
	// into chunks; identity/metadata travels on the first stream message only:
	//
	//	Create/Set:  first message carries id; every message carries a data
	//	             chunk. The server concatenates chunks before decoding.
	//	Update:      first message carries id; updates/preconditions are
	//	             streamed across messages and concatenated by field path.
	//	Get:         the response is streamed. The first message may carry
	//	             not_found; otherwise N messages each carry a data chunk
	//	             that the client concatenates before decoding.
	Create(grpc.ClientStreamingServer[CreateDocumentRequest, CreateDocumentResponse]) error
	Set(grpc.ClientStreamingServer[SetDocumentRequest, DocumentResponse]) error
	Update(grpc.ClientStreamingServer[UpdateDocumentRequest, UpdateDocumentResponse]) error
	Get(*GetDocumentRequest, grpc.ServerStreamingServer[GetDocumentResponse]) error
	Delete(context.Context, *DeleteDocumentRequest) (*DocumentResponse, error)
	List(*ListDocumentRequest, grpc.ServerStreamingServer[ListDocumentResponse]) error
	mustEmbedUnimplementedDocumentStoreServer()
}

// UnimplementedDocumentStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentStoreServer struct{}

func (UnimplementedDocumentStoreServer) Create(grpc.ClientStreamingServer[CreateDocumentRequest, CreateDocumentResponse]) error {
	return status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDocumentStoreServer) Set(grpc.ClientStreamingServer[SetDocumentRequest, DocumentResponse]) error {
	return status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedDocumentStoreServer) Update(grpc.ClientStreamingServer[UpdateDocumentRequest, UpdateDocumentResponse]) error {
	return status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDocumentStoreServer) Get(*GetDocumentRequest, grpc.ServerStreamingServer[GetDocumentResponse]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDocumentStoreServer) Delete(context.Context, *DeleteDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDocumentStoreServer) List(*ListDocumentRequest, grpc.ServerStreamingServer[ListDocumentResponse]) error {
	return status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDocumentStoreServer) mustEmbedUnimplementedDocumentStoreServer() {}
func (UnimplementedDocumentStoreServer) testEmbeddedByValue()                       {}

// UnsafeDocumentStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentStoreServer will
// result in compilation errors.
type UnsafeDocumentStoreServer interface {
	mustEmbedUnimplementedDocumentStoreServer()
}

func RegisterDocumentStoreServer(s grpc.ServiceRegistrar, srv DocumentStoreServer) {
	// If the following call panics, it indicates UnimplementedDocumentStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentStore_ServiceDesc, srv)
}

func _DocumentStore_Create_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentStoreServer).Create(&grpc.GenericServerStream[CreateDocumentRequest, CreateDocumentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_CreateServer = grpc.ClientStreamingServer[CreateDocumentRequest, CreateDocumentResponse]

func _DocumentStore_Set_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentStoreServer).Set(&grpc.GenericServerStream[SetDocumentRequest, DocumentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_SetServer = grpc.ClientStreamingServer[SetDocumentRequest, DocumentResponse]

func _DocumentStore_Update_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentStoreServer).Update(&grpc.GenericServerStream[UpdateDocumentRequest, UpdateDocumentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_UpdateServer = grpc.ClientStreamingServer[UpdateDocumentRequest, UpdateDocumentResponse]

func _DocumentStore_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDocumentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentStoreServer).Get(m, &grpc.GenericServerStream[GetDocumentRequest, GetDocumentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_GetServer = grpc.ServerStreamingServer[GetDocumentResponse]

func _DocumentStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Delete(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDocumentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentStoreServer).List(m, &grpc.GenericServerStream[ListDocumentRequest, ListDocumentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentStore_ListServer = grpc.ServerStreamingServer[ListDocumentResponse]

// DocumentStore_ServiceDesc is the grpc.ServiceDesc for DocumentStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DocumentStore",
	HandlerType: (*DocumentStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _DocumentStore_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Create",
			Handler:       _DocumentStore_Create_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Set",
			Handler:       _DocumentStore_Set_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Update",
			Handler:       _DocumentStore_Update_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _DocumentStore_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "List",
			Handler:       _DocumentStore_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "docpb/datastore.proto",
}
