// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: commandrpc/command.proto

package commandrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Command_SubscribeCommand_FullMethodName     = "/command.Command/SubscribeCommand"
	Command_SubscribeREPLCommand_FullMethodName = "/command.Command/SubscribeREPLCommand"
)

// CommandClient is the client API for Command service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandClient interface {
	SubscribeCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientCommandMessage, ServerCommandMessage], error)
	SubscribeREPLCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientREPLCommandMessage, ServerREPLCommandMessage], error)
}

type commandClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandClient(cc grpc.ClientConnInterface) CommandClient {
	return &commandClient{cc}
}

func (c *commandClient) SubscribeCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientCommandMessage, ServerCommandMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Command_ServiceDesc.Streams[0], Command_SubscribeCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientCommandMessage, ServerCommandMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeCommandClient = grpc.BidiStreamingClient[ClientCommandMessage, ServerCommandMessage]

func (c *commandClient) SubscribeREPLCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientREPLCommandMessage, ServerREPLCommandMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Command_ServiceDesc.Streams[1], Command_SubscribeREPLCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientREPLCommandMessage, ServerREPLCommandMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeREPLCommandClient = grpc.BidiStreamingClient[ClientREPLCommandMessage, ServerREPLCommandMessage]

// CommandServer is the server API for Command service.
// All implementations must embed UnimplementedCommandServer
// for forward compatibility.
type CommandServer interface {
	SubscribeCommand(grpc.BidiStreamingServer[ClientCommandMessage, ServerCommandMessage]) error
	SubscribeREPLCommand(grpc.BidiStreamingServer[ClientREPLCommandMessage, ServerREPLCommandMessage]) error
	mustEmbedUnimplementedCommandServer()
}

// UnimplementedCommandServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServer struct{}

func (UnimplementedCommandServer) SubscribeCommand(grpc.BidiStreamingServer[ClientCommandMessage, ServerCommandMessage]) error {
	return status.Error(codes.Unimplemented, "method SubscribeCommand not implemented")
}
func (UnimplementedCommandServer) SubscribeREPLCommand(grpc.BidiStreamingServer[ClientREPLCommandMessage, ServerREPLCommandMessage]) error {
	return status.Error(codes.Unimplemented, "method SubscribeREPLCommand not implemented")
}
func (UnimplementedCommandServer) mustEmbedUnimplementedCommandServer() {}
func (UnimplementedCommandServer) testEmbeddedByValue()                 {}

// UnsafeCommandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServer will
// result in compilation errors.
type UnsafeCommandServer interface {
	mustEmbedUnimplementedCommandServer()
}

func RegisterCommandServer(s grpc.ServiceRegistrar, srv CommandServer) {
	// If the following call panics, it indicates UnimplementedCommandServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Command_ServiceDesc, srv)
}

func _Command_SubscribeCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandServer).SubscribeCommand(&grpc.GenericServerStream[ClientCommandMessage, ServerCommandMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeCommandServer = grpc.BidiStreamingServer[ClientCommandMessage, ServerCommandMessage]

func _Command_SubscribeREPLCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandServer).SubscribeREPLCommand(&grpc.GenericServerStream[ClientREPLCommandMessage, ServerREPLCommandMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeREPLCommandServer = grpc.BidiStreamingServer[ClientREPLCommandMessage, ServerREPLCommandMessage]

// Command_ServiceDesc is the grpc.ServiceDesc for Command service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Command_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "command.Command",
	HandlerType: (*CommandServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeCommand",
			Handler:       _Command_SubscribeCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeREPLCommand",
			Handler:       _Command_SubscribeREPLCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "commandrpc/command.proto",
}
