// Copyright 2026 Unstable Build, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkgrpc/pkg.proto

package pkgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LibDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PkgId         string                 `protobuf:"bytes,1,opt,name=pkg_id,json=pkgId,proto3" json:"pkg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibDirRequest) Reset() {
	*x = LibDirRequest{}
	mi := &file_pkgrpc_pkg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibDirRequest) ProtoMessage() {}

func (x *LibDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpc_pkg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibDirRequest.ProtoReflect.Descriptor instead.
func (*LibDirRequest) Descriptor() ([]byte, []int) {
	return file_pkgrpc_pkg_proto_rawDescGZIP(), []int{0}
}

func (x *LibDirRequest) GetPkgId() string {
	if x != nil {
		return x.PkgId
	}
	return ""
}

type LibDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibDirResponse) Reset() {
	*x = LibDirResponse{}
	mi := &file_pkgrpc_pkg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibDirResponse) ProtoMessage() {}

func (x *LibDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgrpc_pkg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibDirResponse.ProtoReflect.Descriptor instead.
func (*LibDirResponse) Descriptor() ([]byte, []int) {
	return file_pkgrpc_pkg_proto_rawDescGZIP(), []int{1}
}

func (x *LibDirResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_pkgrpc_pkg_proto protoreflect.FileDescriptor

const file_pkgrpc_pkg_proto_rawDesc = "" +
	"\n" +
	"\x10pkgrpc/pkg.proto\x12\x03pkg\"&\n" +
	"\rLibDirRequest\x12\x15\n" +
	"\x06pkg_id\x18\x01 \x01(\tR\x05pkgId\"&\n" +
	"\x0eLibDirResponse\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths2?\n" +
	"\bPackages\x123\n" +
	"\x06LibDir\x12\x12.pkg.LibDirRequest\x1a\x13.pkg.LibDirResponse0\x01B8Z6github.com/unstablebuild/rune-go-sdk/api/pkgapi/pkgrpcb\x06proto3"

var (
	file_pkgrpc_pkg_proto_rawDescOnce sync.Once
	file_pkgrpc_pkg_proto_rawDescData []byte
)

func file_pkgrpc_pkg_proto_rawDescGZIP() []byte {
	file_pkgrpc_pkg_proto_rawDescOnce.Do(func() {
		file_pkgrpc_pkg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkgrpc_pkg_proto_rawDesc), len(file_pkgrpc_pkg_proto_rawDesc)))
	})
	return file_pkgrpc_pkg_proto_rawDescData
}

var file_pkgrpc_pkg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkgrpc_pkg_proto_goTypes = []any{
	(*LibDirRequest)(nil),  // 0: pkg.LibDirRequest
	(*LibDirResponse)(nil), // 1: pkg.LibDirResponse
}
var file_pkgrpc_pkg_proto_depIdxs = []int32{
	0, // 0: pkg.Packages.LibDir:input_type -> pkg.LibDirRequest
	1, // 1: pkg.Packages.LibDir:output_type -> pkg.LibDirResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkgrpc_pkg_proto_init() }
func file_pkgrpc_pkg_proto_init() {
	if File_pkgrpc_pkg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkgrpc_pkg_proto_rawDesc), len(file_pkgrpc_pkg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkgrpc_pkg_proto_goTypes,
		DependencyIndexes: file_pkgrpc_pkg_proto_depIdxs,
		MessageInfos:      file_pkgrpc_pkg_proto_msgTypes,
	}.Build()
	File_pkgrpc_pkg_proto = out.File
	file_pkgrpc_pkg_proto_goTypes = nil
	file_pkgrpc_pkg_proto_depIdxs = nil
}
