// Copyright 2026 Unstable Build, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: pkgrpc/pkg.proto

package pkgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Packages_LibDir_FullMethodName = "/pkg.Packages/LibDir"
)

// PackagesClient is the client API for Packages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Packages resolves the Rune packages installed on the workspace host.
type PackagesClient interface {
	// LibDir streams the absolute paths of the files in the in-use
	// version of pkg_id. It may block while the user decides whether to
	// install the package, and fails with NOT_FOUND when the package
	// ends up not installed.
	LibDir(ctx context.Context, in *LibDirRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LibDirResponse], error)
}

type packagesClient struct {
	cc grpc.ClientConnInterface
}

func NewPackagesClient(cc grpc.ClientConnInterface) PackagesClient {
	return &packagesClient{cc}
}

func (c *packagesClient) LibDir(ctx context.Context, in *LibDirRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LibDirResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Packages_ServiceDesc.Streams[0], Packages_LibDir_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LibDirRequest, LibDirResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Packages_LibDirClient = grpc.ServerStreamingClient[LibDirResponse]

// PackagesServer is the server API for Packages service.
// All implementations must embed UnimplementedPackagesServer
// for forward compatibility.
//
// Packages resolves the Rune packages installed on the workspace host.
type PackagesServer interface {
	// LibDir streams the absolute paths of the files in the in-use
	// version of pkg_id. It may block while the user decides whether to
	// install the package, and fails with NOT_FOUND when the package
	// ends up not installed.
	LibDir(*LibDirRequest, grpc.ServerStreamingServer[LibDirResponse]) error
	mustEmbedUnimplementedPackagesServer()
}

// UnimplementedPackagesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPackagesServer struct{}

func (UnimplementedPackagesServer) LibDir(*LibDirRequest, grpc.ServerStreamingServer[LibDirResponse]) error {
	return status.Error(codes.Unimplemented, "method LibDir not implemented")
}
func (UnimplementedPackagesServer) mustEmbedUnimplementedPackagesServer() {}
func (UnimplementedPackagesServer) testEmbeddedByValue()                  {}

// UnsafePackagesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackagesServer will
// result in compilation errors.
type UnsafePackagesServer interface {
	mustEmbedUnimplementedPackagesServer()
}

func RegisterPackagesServer(s grpc.ServiceRegistrar, srv PackagesServer) {
	// If the following call panics, it indicates UnimplementedPackagesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Packages_ServiceDesc, srv)
}

func _Packages_LibDir_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LibDirRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackagesServer).LibDir(m, &grpc.GenericServerStream[LibDirRequest, LibDirResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Packages_LibDirServer = grpc.ServerStreamingServer[LibDirResponse]

// Packages_ServiceDesc is the grpc.ServiceDesc for Packages service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Packages_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.Packages",
	HandlerType: (*PackagesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LibDir",
			Handler:       _Packages_LibDir_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkgrpc/pkg.proto",
}
