// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: llmrpc/llm.proto

package llmrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_ASSISTANT   Role = 1
	Role_ROLE_USER        Role = 2
	Role_ROLE_SYSTEM      Role = 3
	Role_ROLE_TOOL        Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_ASSISTANT",
		2: "ROLE_USER",
		3: "ROLE_SYSTEM",
		4: "ROLE_TOOL",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_ASSISTANT":   1,
		"ROLE_USER":        2,
		"ROLE_SYSTEM":      3,
		"ROLE_TOOL":        4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_llmrpc_llm_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_llmrpc_llm_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{0}
}

type ToolType int32

const (
	ToolType_TOOL_TYPE_UNSPECIFIED ToolType = 0
	ToolType_TOOL_TYPE_FUNCTION    ToolType = 1
)

// Enum value maps for ToolType.
var (
	ToolType_name = map[int32]string{
		0: "TOOL_TYPE_UNSPECIFIED",
		1: "TOOL_TYPE_FUNCTION",
	}
	ToolType_value = map[string]int32{
		"TOOL_TYPE_UNSPECIFIED": 0,
		"TOOL_TYPE_FUNCTION":    1,
	}
)

func (x ToolType) Enum() *ToolType {
	p := new(ToolType)
	*p = x
	return p
}

func (x ToolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolType) Descriptor() protoreflect.EnumDescriptor {
	return file_llmrpc_llm_proto_enumTypes[1].Descriptor()
}

func (ToolType) Type() protoreflect.EnumType {
	return &file_llmrpc_llm_proto_enumTypes[1]
}

func (x ToolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolType.Descriptor instead.
func (ToolType) EnumDescriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{1}
}

type ContentPartType int32

const (
	ContentPartType_CONTENT_PART_TYPE_TEXT      ContentPartType = 0
	ContentPartType_CONTENT_PART_TYPE_IMAGE_URL ContentPartType = 1
)

// Enum value maps for ContentPartType.
var (
	ContentPartType_name = map[int32]string{
		0: "CONTENT_PART_TYPE_TEXT",
		1: "CONTENT_PART_TYPE_IMAGE_URL",
	}
	ContentPartType_value = map[string]int32{
		"CONTENT_PART_TYPE_TEXT":      0,
		"CONTENT_PART_TYPE_IMAGE_URL": 1,
	}
)

func (x ContentPartType) Enum() *ContentPartType {
	p := new(ContentPartType)
	*p = x
	return p
}

func (x ContentPartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentPartType) Descriptor() protoreflect.EnumDescriptor {
	return file_llmrpc_llm_proto_enumTypes[2].Descriptor()
}

func (ContentPartType) Type() protoreflect.EnumType {
	return &file_llmrpc_llm_proto_enumTypes[2]
}

func (x ContentPartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentPartType.Descriptor instead.
func (ContentPartType) EnumDescriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{2}
}

type EventType int32

const (
	EventType_EVENT_TYPE_TEXT_DELTA         EventType = 0
	EventType_EVENT_TYPE_REASONING_DELTA    EventType = 1
	EventType_EVENT_TYPE_TOOL_CALL_DONE     EventType = 2
	EventType_EVENT_TYPE_STREAM_DONE        EventType = 3
	EventType_EVENT_TYPE_STREAM_ERROR       EventType = 4
	EventType_EVENT_TYPE_STREAM_RESET       EventType = 5
	EventType_EVENT_TYPE_RATE_LIMIT_WARNING EventType = 6
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_TEXT_DELTA",
		1: "EVENT_TYPE_REASONING_DELTA",
		2: "EVENT_TYPE_TOOL_CALL_DONE",
		3: "EVENT_TYPE_STREAM_DONE",
		4: "EVENT_TYPE_STREAM_ERROR",
		5: "EVENT_TYPE_STREAM_RESET",
		6: "EVENT_TYPE_RATE_LIMIT_WARNING",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_TEXT_DELTA":         0,
		"EVENT_TYPE_REASONING_DELTA":    1,
		"EVENT_TYPE_TOOL_CALL_DONE":     2,
		"EVENT_TYPE_STREAM_DONE":        3,
		"EVENT_TYPE_STREAM_ERROR":       4,
		"EVENT_TYPE_STREAM_RESET":       5,
		"EVENT_TYPE_RATE_LIMIT_WARNING": 6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_llmrpc_llm_proto_enumTypes[3].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_llmrpc_llm_proto_enumTypes[3]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{3}
}

type ContentPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ContentPartType        `protobuf:"varint,1,opt,name=type,proto3,enum=llm.ContentPartType" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentPart) Reset() {
	*x = ContentPart{}
	mi := &file_llmrpc_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPart) ProtoMessage() {}

func (x *ContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPart.ProtoReflect.Descriptor instead.
func (*ContentPart) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{0}
}

func (x *ContentPart) GetType() ContentPartType {
	if x != nil {
		return x.Type
	}
	return ContentPartType_CONTENT_PART_TYPE_TEXT
}

func (x *ContentPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ContentPart) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type FunctionCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_llmrpc_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ToolType               `protobuf:"varint,2,opt,name=type,proto3,enum=llm.ToolType" json:"type,omitempty"`
	Function      *FunctionCall          `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_llmrpc_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() ToolType {
	if x != nil {
		return x.Type
	}
	return ToolType_TOOL_TYPE_UNSPECIFIED
}

func (x *ToolCall) GetFunction() *FunctionCall {
	if x != nil {
		return x.Function
	}
	return nil
}

type ReasoningBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningBlock) Reset() {
	*x = ReasoningBlock{}
	mi := &file_llmrpc_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningBlock) ProtoMessage() {}

func (x *ReasoningBlock) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningBlock.ProtoReflect.Descriptor instead.
func (*ReasoningBlock) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{3}
}

func (x *ReasoningBlock) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ReasoningBlock) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReasoningBlock) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ReasoningBlock) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Message struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Role             Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=llm.Role" json:"role,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ReasoningContent string                 `protobuf:"bytes,3,opt,name=reasoning_content,json=reasoningContent,proto3" json:"reasoning_content,omitempty"`
	MultiContent     []*ContentPart         `protobuf:"bytes,4,rep,name=multi_content,json=multiContent,proto3" json:"multi_content,omitempty"`
	ToolCalls        []*ToolCall            `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolCallId       string                 `protobuf:"bytes,6,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Name             string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	ReasoningBlocks  []*ReasoningBlock      `protobuf:"bytes,8,rep,name=reasoning_blocks,json=reasoningBlocks,proto3" json:"reasoning_blocks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_llmrpc_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetReasoningContent() string {
	if x != nil {
		return x.ReasoningContent
	}
	return ""
}

func (x *Message) GetMultiContent() []*ContentPart {
	if x != nil {
		return x.MultiContent
	}
	return nil
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetReasoningBlocks() []*ReasoningBlock {
	if x != nil {
		return x.ReasoningBlocks
	}
	return nil
}

type FunctionDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Parameters serialized as JSON.
	Parameters    []byte `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDefinition) Reset() {
	*x = FunctionDefinition{}
	mi := &file_llmrpc_llm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDefinition) ProtoMessage() {}

func (x *FunctionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDefinition.ProtoReflect.Descriptor instead.
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{5}
}

func (x *FunctionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDefinition) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ToolType               `protobuf:"varint,1,opt,name=type,proto3,enum=llm.ToolType" json:"type,omitempty"`
	Function      *FunctionDefinition    `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_llmrpc_llm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{6}
}

func (x *Tool) GetType() ToolType {
	if x != nil {
		return x.Type
	}
	return ToolType_TOOL_TYPE_UNSPECIFIED
}

func (x *Tool) GetFunction() *FunctionDefinition {
	if x != nil {
		return x.Function
	}
	return nil
}

type ResponseFormatJSONSchema struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Schema serialized as JSON.
	Schema        []byte `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Strict        bool   `protobuf:"varint,4,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFormatJSONSchema) Reset() {
	*x = ResponseFormatJSONSchema{}
	mi := &file_llmrpc_llm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFormatJSONSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFormatJSONSchema) ProtoMessage() {}

func (x *ResponseFormatJSONSchema) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFormatJSONSchema.ProtoReflect.Descriptor instead.
func (*ResponseFormatJSONSchema) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseFormatJSONSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseFormatJSONSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseFormatJSONSchema) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ResponseFormatJSONSchema) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

type ResponseFormat struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          string                    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	JsonSchema    *ResponseFormatJSONSchema `protobuf:"bytes,2,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	HasJsonSchema bool                      `protobuf:"varint,3,opt,name=has_json_schema,json=hasJsonSchema,proto3" json:"has_json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFormat) Reset() {
	*x = ResponseFormat{}
	mi := &file_llmrpc_llm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFormat) ProtoMessage() {}

func (x *ResponseFormat) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFormat.ProtoReflect.Descriptor instead.
func (*ResponseFormat) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseFormat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResponseFormat) GetJsonSchema() *ResponseFormatJSONSchema {
	if x != nil {
		return x.JsonSchema
	}
	return nil
}

func (x *ResponseFormat) GetHasJsonSchema() bool {
	if x != nil {
		return x.HasJsonSchema
	}
	return false
}

type Request struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Messages          []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools             []*Tool                `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	ReasoningEffort   string                 `protobuf:"bytes,3,opt,name=reasoning_effort,json=reasoningEffort,proto3" json:"reasoning_effort,omitempty"`
	ReasoningSummary  string                 `protobuf:"bytes,4,opt,name=reasoning_summary,json=reasoningSummary,proto3" json:"reasoning_summary,omitempty"`
	MaxOutputTokens   int32                  `protobuf:"varint,5,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	ResponseFormat    *ResponseFormat        `protobuf:"bytes,6,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"`
	HasResponseFormat bool                   `protobuf:"varint,7,opt,name=has_response_format,json=hasResponseFormat,proto3" json:"has_response_format,omitempty"`
	PromptCacheKey    string                 `protobuf:"bytes,8,opt,name=prompt_cache_key,json=promptCacheKey,proto3" json:"prompt_cache_key,omitempty"`
	TokenCount        int32                  `protobuf:"varint,9,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_llmrpc_llm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{9}
}

func (x *Request) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Request) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Request) GetReasoningEffort() string {
	if x != nil {
		return x.ReasoningEffort
	}
	return ""
}

func (x *Request) GetReasoningSummary() string {
	if x != nil {
		return x.ReasoningSummary
	}
	return ""
}

func (x *Request) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *Request) GetResponseFormat() *ResponseFormat {
	if x != nil {
		return x.ResponseFormat
	}
	return nil
}

func (x *Request) GetHasResponseFormat() bool {
	if x != nil {
		return x.HasResponseFormat
	}
	return false
}

func (x *Request) GetPromptCacheKey() string {
	if x != nil {
		return x.PromptCacheKey
	}
	return ""
}

func (x *Request) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

type Usage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TokensSent         int32                  `protobuf:"varint,1,opt,name=tokens_sent,json=tokensSent,proto3" json:"tokens_sent,omitempty"`
	TokensReceived     int32                  `protobuf:"varint,2,opt,name=tokens_received,json=tokensReceived,proto3" json:"tokens_received,omitempty"`
	TokensReasoned     int32                  `protobuf:"varint,3,opt,name=tokens_reasoned,json=tokensReasoned,proto3" json:"tokens_reasoned,omitempty"`
	TokensCached       int32                  `protobuf:"varint,4,opt,name=tokens_cached,json=tokensCached,proto3" json:"tokens_cached,omitempty"`
	TokensCacheCreated int32                  `protobuf:"varint,5,opt,name=tokens_cache_created,json=tokensCacheCreated,proto3" json:"tokens_cache_created,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_llmrpc_llm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{10}
}

func (x *Usage) GetTokensSent() int32 {
	if x != nil {
		return x.TokensSent
	}
	return 0
}

func (x *Usage) GetTokensReceived() int32 {
	if x != nil {
		return x.TokensReceived
	}
	return 0
}

func (x *Usage) GetTokensReasoned() int32 {
	if x != nil {
		return x.TokensReasoned
	}
	return 0
}

func (x *Usage) GetTokensCached() int32 {
	if x != nil {
		return x.TokensCached
	}
	return 0
}

func (x *Usage) GetTokensCacheCreated() int32 {
	if x != nil {
		return x.TokensCacheCreated
	}
	return 0
}

type DoneData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason  string                 `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneData) Reset() {
	*x = DoneData{}
	mi := &file_llmrpc_llm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneData) ProtoMessage() {}

func (x *DoneData) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneData.ProtoReflect.Descriptor instead.
func (*DoneData) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{11}
}

func (x *DoneData) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *DoneData) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *DoneData) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type RateLimitInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WaitDurationNs int64                  `protobuf:"varint,1,opt,name=wait_duration_ns,json=waitDurationNs,proto3" json:"wait_duration_ns,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RateLimitInfo) Reset() {
	*x = RateLimitInfo{}
	mi := &file_llmrpc_llm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitInfo) ProtoMessage() {}

func (x *RateLimitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitInfo.ProtoReflect.Descriptor instead.
func (*RateLimitInfo) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{12}
}

func (x *RateLimitInfo) GetWaitDurationNs() int64 {
	if x != nil {
		return x.WaitDurationNs
	}
	return 0
}

func (x *RateLimitInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=llm.EventType" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Reasoning     string                 `protobuf:"bytes,3,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	ToolCall      *ToolCall              `protobuf:"bytes,4,opt,name=tool_call,json=toolCall,proto3" json:"tool_call,omitempty"`
	DoneData      *DoneData              `protobuf:"bytes,5,opt,name=done_data,json=doneData,proto3" json:"done_data,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	RateLimit     *RateLimitInfo         `protobuf:"bytes,7,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_llmrpc_llm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{13}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_TEXT_DELTA
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Event) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *Event) GetToolCall() *ToolCall {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

func (x *Event) GetDoneData() *DoneData {
	if x != nil {
		return x.DoneData
	}
	return nil
}

func (x *Event) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Event) GetRateLimit() *RateLimitInfo {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

type ModelEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ContextWindow int32                  `protobuf:"varint,3,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelEntry) Reset() {
	*x = ModelEntry{}
	mi := &file_llmrpc_llm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelEntry) ProtoMessage() {}

func (x *ModelEntry) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelEntry.ProtoReflect.Descriptor instead.
func (*ModelEntry) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{14}
}

func (x *ModelEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelEntry) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelEntry) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *ModelEntry) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

// CompletionHeader carries every Request field except the repeated messages,
// which are streamed separately as CreateCompletionRequestChunk message frames.
type CompletionHeader struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             *ModelEntry            `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Tools             []*Tool                `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	ReasoningEffort   string                 `protobuf:"bytes,3,opt,name=reasoning_effort,json=reasoningEffort,proto3" json:"reasoning_effort,omitempty"`
	ReasoningSummary  string                 `protobuf:"bytes,4,opt,name=reasoning_summary,json=reasoningSummary,proto3" json:"reasoning_summary,omitempty"`
	MaxOutputTokens   int32                  `protobuf:"varint,5,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	ResponseFormat    *ResponseFormat        `protobuf:"bytes,6,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"`
	HasResponseFormat bool                   `protobuf:"varint,7,opt,name=has_response_format,json=hasResponseFormat,proto3" json:"has_response_format,omitempty"`
	PromptCacheKey    string                 `protobuf:"bytes,8,opt,name=prompt_cache_key,json=promptCacheKey,proto3" json:"prompt_cache_key,omitempty"`
	TokenCount        int32                  `protobuf:"varint,9,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompletionHeader) Reset() {
	*x = CompletionHeader{}
	mi := &file_llmrpc_llm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionHeader) ProtoMessage() {}

func (x *CompletionHeader) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionHeader.ProtoReflect.Descriptor instead.
func (*CompletionHeader) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{15}
}

func (x *CompletionHeader) GetModel() *ModelEntry {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *CompletionHeader) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *CompletionHeader) GetReasoningEffort() string {
	if x != nil {
		return x.ReasoningEffort
	}
	return ""
}

func (x *CompletionHeader) GetReasoningSummary() string {
	if x != nil {
		return x.ReasoningSummary
	}
	return ""
}

func (x *CompletionHeader) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *CompletionHeader) GetResponseFormat() *ResponseFormat {
	if x != nil {
		return x.ResponseFormat
	}
	return nil
}

func (x *CompletionHeader) GetHasResponseFormat() bool {
	if x != nil {
		return x.HasResponseFormat
	}
	return false
}

func (x *CompletionHeader) GetPromptCacheKey() string {
	if x != nil {
		return x.PromptCacheKey
	}
	return ""
}

func (x *CompletionHeader) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

// CreateCompletionRequestChunk is one frame of a client-streamed
// CreateCompletion request: exactly one header frame first, then zero or more
// message frames in order. Streaming typed frames keeps each gRPC message small
// so long histories no longer hit the per-message receive limit.
type CreateCompletionRequestChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CreateCompletionRequestChunk_Header
	//	*CreateCompletionRequestChunk_Message
	Payload       isCreateCompletionRequestChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompletionRequestChunk) Reset() {
	*x = CreateCompletionRequestChunk{}
	mi := &file_llmrpc_llm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompletionRequestChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompletionRequestChunk) ProtoMessage() {}

func (x *CreateCompletionRequestChunk) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompletionRequestChunk.ProtoReflect.Descriptor instead.
func (*CreateCompletionRequestChunk) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCompletionRequestChunk) GetPayload() isCreateCompletionRequestChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateCompletionRequestChunk) GetHeader() *CompletionHeader {
	if x != nil {
		if x, ok := x.Payload.(*CreateCompletionRequestChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *CreateCompletionRequestChunk) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Payload.(*CreateCompletionRequestChunk_Message); ok {
			return x.Message
		}
	}
	return nil
}

type isCreateCompletionRequestChunk_Payload interface {
	isCreateCompletionRequestChunk_Payload()
}

type CreateCompletionRequestChunk_Header struct {
	Header *CompletionHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type CreateCompletionRequestChunk_Message struct {
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

func (*CreateCompletionRequestChunk_Header) isCreateCompletionRequestChunk_Payload() {}

func (*CreateCompletionRequestChunk_Message) isCreateCompletionRequestChunk_Payload() {}

// CreateCompletionResponseChunk is one frame of the server-streamed
// CreateCompletion response: each frame carries a single logical Event.
type CreateCompletionResponseChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompletionResponseChunk) Reset() {
	*x = CreateCompletionResponseChunk{}
	mi := &file_llmrpc_llm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompletionResponseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompletionResponseChunk) ProtoMessage() {}

func (x *CreateCompletionResponseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompletionResponseChunk.ProtoReflect.Descriptor instead.
func (*CreateCompletionResponseChunk) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCompletionResponseChunk) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type CountTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ModelEntry            `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountTokensRequest) Reset() {
	*x = CountTokensRequest{}
	mi := &file_llmrpc_llm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensRequest) ProtoMessage() {}

func (x *CountTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensRequest.ProtoReflect.Descriptor instead.
func (*CountTokensRequest) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{18}
}

func (x *CountTokensRequest) GetModel() *ModelEntry {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *CountTokensRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CountTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountTokensResponse) Reset() {
	*x = CountTokensResponse{}
	mi := &file_llmrpc_llm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensResponse) ProtoMessage() {}

func (x *CountTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensResponse.ProtoReflect.Descriptor instead.
func (*CountTokensResponse) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{19}
}

func (x *CountTokensResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsRequest) Reset() {
	*x = ModelsRequest{}
	mi := &file_llmrpc_llm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsRequest) ProtoMessage() {}

func (x *ModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsRequest.ProtoReflect.Descriptor instead.
func (*ModelsRequest) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{20}
}

type ModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ModelEntry            `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsResponse) Reset() {
	*x = ModelsResponse{}
	mi := &file_llmrpc_llm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsResponse) ProtoMessage() {}

func (x *ModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsResponse.ProtoReflect.Descriptor instead.
func (*ModelsResponse) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{21}
}

func (x *ModelsResponse) GetModel() *ModelEntry {
	if x != nil {
		return x.Model
	}
	return nil
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ModelEntry            `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_llmrpc_llm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{22}
}

func (x *GetModelRequest) GetModel() *ModelEntry {
	if x != nil {
		return x.Model
	}
	return nil
}

type GetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ModelEntry            `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
	mi := &file_llmrpc_llm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResponse.ProtoReflect.Descriptor instead.
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{23}
}

func (x *GetModelResponse) GetModel() *ModelEntry {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *GetModelResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// ContextWindowExceededDetail is attached to gRPC error details when the
// host signals ErrContextWindowExceeded.
type ContextWindowExceededDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextWindowExceededDetail) Reset() {
	*x = ContextWindowExceededDetail{}
	mi := &file_llmrpc_llm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextWindowExceededDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextWindowExceededDetail) ProtoMessage() {}

func (x *ContextWindowExceededDetail) ProtoReflect() protoreflect.Message {
	mi := &file_llmrpc_llm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextWindowExceededDetail.ProtoReflect.Descriptor instead.
func (*ContextWindowExceededDetail) Descriptor() ([]byte, []int) {
	return file_llmrpc_llm_proto_rawDescGZIP(), []int{24}
}

func (x *ContextWindowExceededDetail) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ContextWindowExceededDetail) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_llmrpc_llm_proto protoreflect.FileDescriptor

const file_llmrpc_llm_proto_rawDesc = "" +
	"\n" +
	"\x10llmrpc/llm.proto\x12\x03llm\"h\n" +
	"\vContentPart\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.llm.ContentPartTypeR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\"@\n" +
	"\fFunctionCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"l\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04type\x18\x02 \x01(\x0e2\r.llm.ToolTypeR\x04type\x12-\n" +
	"\bfunction\x18\x03 \x01(\v2\x11.llm.FunctionCallR\bfunction\"j\n" +
	"\x0eReasoningBlock\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"\xca\x02\n" +
	"\aMessage\x12\x1d\n" +
	"\x04role\x18\x01 \x01(\x0e2\t.llm.RoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12+\n" +
	"\x11reasoning_content\x18\x03 \x01(\tR\x10reasoningContent\x125\n" +
	"\rmulti_content\x18\x04 \x03(\v2\x10.llm.ContentPartR\fmultiContent\x12,\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\r.llm.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\x06 \x01(\tR\n" +
	"toolCallId\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12>\n" +
	"\x10reasoning_blocks\x18\b \x03(\v2\x13.llm.ReasoningBlockR\x0freasoningBlocks\"j\n" +
	"\x12FunctionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\fR\n" +
	"parameters\"^\n" +
	"\x04Tool\x12!\n" +
	"\x04type\x18\x01 \x01(\x0e2\r.llm.ToolTypeR\x04type\x123\n" +
	"\bfunction\x18\x02 \x01(\v2\x17.llm.FunctionDefinitionR\bfunction\"\x80\x01\n" +
	"\x18ResponseFormatJSONSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\fR\x06schema\x12\x16\n" +
	"\x06strict\x18\x04 \x01(\bR\x06strict\"\x8c\x01\n" +
	"\x0eResponseFormat\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12>\n" +
	"\vjson_schema\x18\x02 \x01(\v2\x1d.llm.ResponseFormatJSONSchemaR\n" +
	"jsonSchema\x12&\n" +
	"\x0fhas_json_schema\x18\x03 \x01(\bR\rhasJsonSchema\"\x91\x03\n" +
	"\aRequest\x12(\n" +
	"\bmessages\x18\x01 \x03(\v2\f.llm.MessageR\bmessages\x12\x1f\n" +
	"\x05tools\x18\x02 \x03(\v2\t.llm.ToolR\x05tools\x12)\n" +
	"\x10reasoning_effort\x18\x03 \x01(\tR\x0freasoningEffort\x12+\n" +
	"\x11reasoning_summary\x18\x04 \x01(\tR\x10reasoningSummary\x12*\n" +
	"\x11max_output_tokens\x18\x05 \x01(\x05R\x0fmaxOutputTokens\x12<\n" +
	"\x0fresponse_format\x18\x06 \x01(\v2\x13.llm.ResponseFormatR\x0eresponseFormat\x12.\n" +
	"\x13has_response_format\x18\a \x01(\bR\x11hasResponseFormat\x12(\n" +
	"\x10prompt_cache_key\x18\b \x01(\tR\x0epromptCacheKey\x12\x1f\n" +
	"\vtoken_count\x18\t \x01(\x05R\n" +
	"tokenCount\"\xd1\x01\n" +
	"\x05Usage\x12\x1f\n" +
	"\vtokens_sent\x18\x01 \x01(\x05R\n" +
	"tokensSent\x12'\n" +
	"\x0ftokens_received\x18\x02 \x01(\x05R\x0etokensReceived\x12'\n" +
	"\x0ftokens_reasoned\x18\x03 \x01(\x05R\x0etokensReasoned\x12#\n" +
	"\rtokens_cached\x18\x04 \x01(\x05R\ftokensCached\x120\n" +
	"\x14tokens_cache_created\x18\x05 \x01(\x05R\x12tokensCacheCreated\"y\n" +
	"\bDoneData\x12&\n" +
	"\amessage\x18\x01 \x01(\v2\f.llm.MessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x02 \x01(\tR\ffinishReason\x12 \n" +
	"\x05usage\x18\x03 \x01(\v2\n" +
	".llm.UsageR\x05usage\"S\n" +
	"\rRateLimitInfo\x12(\n" +
	"\x10wait_duration_ns\x18\x01 \x01(\x03R\x0ewaitDurationNs\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfe\x01\n" +
	"\x05Event\x12\"\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0e.llm.EventTypeR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\treasoning\x18\x03 \x01(\tR\treasoning\x12*\n" +
	"\ttool_call\x18\x04 \x01(\v2\r.llm.ToolCallR\btoolCall\x12*\n" +
	"\tdone_data\x18\x05 \x01(\v2\r.llm.DoneDataR\bdoneData\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x121\n" +
	"\n" +
	"rate_limit\x18\a \x01(\v2\x12.llm.RateLimitInfoR\trateLimit\"~\n" +
	"\n" +
	"ModelEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12%\n" +
	"\x0econtext_window\x18\x03 \x01(\x05R\rcontextWindow\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\"\x97\x03\n" +
	"\x10CompletionHeader\x12%\n" +
	"\x05model\x18\x01 \x01(\v2\x0f.llm.ModelEntryR\x05model\x12\x1f\n" +
	"\x05tools\x18\x02 \x03(\v2\t.llm.ToolR\x05tools\x12)\n" +
	"\x10reasoning_effort\x18\x03 \x01(\tR\x0freasoningEffort\x12+\n" +
	"\x11reasoning_summary\x18\x04 \x01(\tR\x10reasoningSummary\x12*\n" +
	"\x11max_output_tokens\x18\x05 \x01(\x05R\x0fmaxOutputTokens\x12<\n" +
	"\x0fresponse_format\x18\x06 \x01(\v2\x13.llm.ResponseFormatR\x0eresponseFormat\x12.\n" +
	"\x13has_response_format\x18\a \x01(\bR\x11hasResponseFormat\x12(\n" +
	"\x10prompt_cache_key\x18\b \x01(\tR\x0epromptCacheKey\x12\x1f\n" +
	"\vtoken_count\x18\t \x01(\x05R\n" +
	"tokenCount\"\x84\x01\n" +
	"\x1cCreateCompletionRequestChunk\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x15.llm.CompletionHeaderH\x00R\x06header\x12(\n" +
	"\amessage\x18\x02 \x01(\v2\f.llm.MessageH\x00R\amessageB\t\n" +
	"\apayload\"A\n" +
	"\x1dCreateCompletionResponseChunk\x12 \n" +
	"\x05event\x18\x01 \x01(\v2\n" +
	".llm.EventR\x05event\"e\n" +
	"\x12CountTokensRequest\x12%\n" +
	"\x05model\x18\x01 \x01(\v2\x0f.llm.ModelEntryR\x05model\x12(\n" +
	"\bmessages\x18\x02 \x03(\v2\f.llm.MessageR\bmessages\"+\n" +
	"\x13CountTokensResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x0f\n" +
	"\rModelsRequest\"7\n" +
	"\x0eModelsResponse\x12%\n" +
	"\x05model\x18\x01 \x01(\v2\x0f.llm.ModelEntryR\x05model\"8\n" +
	"\x0fGetModelRequest\x12%\n" +
	"\x05model\x18\x01 \x01(\v2\x0f.llm.ModelEntryR\x05model\"O\n" +
	"\x10GetModelResponse\x12%\n" +
	"\x05model\x18\x01 \x01(\v2\x0f.llm.ModelEntryR\x05model\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"E\n" +
	"\x1bContextWindowExceededDetail\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max*_\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x01\x12\r\n" +
	"\tROLE_USER\x10\x02\x12\x0f\n" +
	"\vROLE_SYSTEM\x10\x03\x12\r\n" +
	"\tROLE_TOOL\x10\x04*=\n" +
	"\bToolType\x12\x19\n" +
	"\x15TOOL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TOOL_TYPE_FUNCTION\x10\x01*N\n" +
	"\x0fContentPartType\x12\x1a\n" +
	"\x16CONTENT_PART_TYPE_TEXT\x10\x00\x12\x1f\n" +
	"\x1bCONTENT_PART_TYPE_IMAGE_URL\x10\x01*\xde\x01\n" +
	"\tEventType\x12\x19\n" +
	"\x15EVENT_TYPE_TEXT_DELTA\x10\x00\x12\x1e\n" +
	"\x1aEVENT_TYPE_REASONING_DELTA\x10\x01\x12\x1d\n" +
	"\x19EVENT_TYPE_TOOL_CALL_DONE\x10\x02\x12\x1a\n" +
	"\x16EVENT_TYPE_STREAM_DONE\x10\x03\x12\x1b\n" +
	"\x17EVENT_TYPE_STREAM_ERROR\x10\x04\x12\x1b\n" +
	"\x17EVENT_TYPE_STREAM_RESET\x10\x05\x12!\n" +
	"\x1dEVENT_TYPE_RATE_LIMIT_WARNING\x10\x062\x94\x02\n" +
	"\x03LLM\x12]\n" +
	"\x10CreateCompletion\x12!.llm.CreateCompletionRequestChunk\x1a\".llm.CreateCompletionResponseChunk(\x010\x01\x12@\n" +
	"\vCountTokens\x12\x17.llm.CountTokensRequest\x1a\x18.llm.CountTokensResponse\x123\n" +
	"\x06Models\x12\x12.llm.ModelsRequest\x1a\x13.llm.ModelsResponse0\x01\x127\n" +
	"\bGetModel\x12\x14.llm.GetModelRequest\x1a\x15.llm.GetModelResponseB8Z6github.com/unstablebuild/rune-go-sdk/api/llmapi/llmrpcb\x06proto3"

var (
	file_llmrpc_llm_proto_rawDescOnce sync.Once
	file_llmrpc_llm_proto_rawDescData []byte
)

func file_llmrpc_llm_proto_rawDescGZIP() []byte {
	file_llmrpc_llm_proto_rawDescOnce.Do(func() {
		file_llmrpc_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmrpc_llm_proto_rawDesc), len(file_llmrpc_llm_proto_rawDesc)))
	})
	return file_llmrpc_llm_proto_rawDescData
}

var file_llmrpc_llm_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_llmrpc_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_llmrpc_llm_proto_goTypes = []any{
	(Role)(0),                             // 0: llm.Role
	(ToolType)(0),                         // 1: llm.ToolType
	(ContentPartType)(0),                  // 2: llm.ContentPartType
	(EventType)(0),                        // 3: llm.EventType
	(*ContentPart)(nil),                   // 4: llm.ContentPart
	(*FunctionCall)(nil),                  // 5: llm.FunctionCall
	(*ToolCall)(nil),                      // 6: llm.ToolCall
	(*ReasoningBlock)(nil),                // 7: llm.ReasoningBlock
	(*Message)(nil),                       // 8: llm.Message
	(*FunctionDefinition)(nil),            // 9: llm.FunctionDefinition
	(*Tool)(nil),                          // 10: llm.Tool
	(*ResponseFormatJSONSchema)(nil),      // 11: llm.ResponseFormatJSONSchema
	(*ResponseFormat)(nil),                // 12: llm.ResponseFormat
	(*Request)(nil),                       // 13: llm.Request
	(*Usage)(nil),                         // 14: llm.Usage
	(*DoneData)(nil),                      // 15: llm.DoneData
	(*RateLimitInfo)(nil),                 // 16: llm.RateLimitInfo
	(*Event)(nil),                         // 17: llm.Event
	(*ModelEntry)(nil),                    // 18: llm.ModelEntry
	(*CompletionHeader)(nil),              // 19: llm.CompletionHeader
	(*CreateCompletionRequestChunk)(nil),  // 20: llm.CreateCompletionRequestChunk
	(*CreateCompletionResponseChunk)(nil), // 21: llm.CreateCompletionResponseChunk
	(*CountTokensRequest)(nil),            // 22: llm.CountTokensRequest
	(*CountTokensResponse)(nil),           // 23: llm.CountTokensResponse
	(*ModelsRequest)(nil),                 // 24: llm.ModelsRequest
	(*ModelsResponse)(nil),                // 25: llm.ModelsResponse
	(*GetModelRequest)(nil),               // 26: llm.GetModelRequest
	(*GetModelResponse)(nil),              // 27: llm.GetModelResponse
	(*ContextWindowExceededDetail)(nil),   // 28: llm.ContextWindowExceededDetail
}
var file_llmrpc_llm_proto_depIdxs = []int32{
	2,  // 0: llm.ContentPart.type:type_name -> llm.ContentPartType
	1,  // 1: llm.ToolCall.type:type_name -> llm.ToolType
	5,  // 2: llm.ToolCall.function:type_name -> llm.FunctionCall
	0,  // 3: llm.Message.role:type_name -> llm.Role
	4,  // 4: llm.Message.multi_content:type_name -> llm.ContentPart
	6,  // 5: llm.Message.tool_calls:type_name -> llm.ToolCall
	7,  // 6: llm.Message.reasoning_blocks:type_name -> llm.ReasoningBlock
	1,  // 7: llm.Tool.type:type_name -> llm.ToolType
	9,  // 8: llm.Tool.function:type_name -> llm.FunctionDefinition
	11, // 9: llm.ResponseFormat.json_schema:type_name -> llm.ResponseFormatJSONSchema
	8,  // 10: llm.Request.messages:type_name -> llm.Message
	10, // 11: llm.Request.tools:type_name -> llm.Tool
	12, // 12: llm.Request.response_format:type_name -> llm.ResponseFormat
	8,  // 13: llm.DoneData.message:type_name -> llm.Message
	14, // 14: llm.DoneData.usage:type_name -> llm.Usage
	3,  // 15: llm.Event.type:type_name -> llm.EventType
	6,  // 16: llm.Event.tool_call:type_name -> llm.ToolCall
	15, // 17: llm.Event.done_data:type_name -> llm.DoneData
	16, // 18: llm.Event.rate_limit:type_name -> llm.RateLimitInfo
	18, // 19: llm.CompletionHeader.model:type_name -> llm.ModelEntry
	10, // 20: llm.CompletionHeader.tools:type_name -> llm.Tool
	12, // 21: llm.CompletionHeader.response_format:type_name -> llm.ResponseFormat
	19, // 22: llm.CreateCompletionRequestChunk.header:type_name -> llm.CompletionHeader
	8,  // 23: llm.CreateCompletionRequestChunk.message:type_name -> llm.Message
	17, // 24: llm.CreateCompletionResponseChunk.event:type_name -> llm.Event
	18, // 25: llm.CountTokensRequest.model:type_name -> llm.ModelEntry
	8,  // 26: llm.CountTokensRequest.messages:type_name -> llm.Message
	18, // 27: llm.ModelsResponse.model:type_name -> llm.ModelEntry
	18, // 28: llm.GetModelRequest.model:type_name -> llm.ModelEntry
	18, // 29: llm.GetModelResponse.model:type_name -> llm.ModelEntry
	20, // 30: llm.LLM.CreateCompletion:input_type -> llm.CreateCompletionRequestChunk
	22, // 31: llm.LLM.CountTokens:input_type -> llm.CountTokensRequest
	24, // 32: llm.LLM.Models:input_type -> llm.ModelsRequest
	26, // 33: llm.LLM.GetModel:input_type -> llm.GetModelRequest
	21, // 34: llm.LLM.CreateCompletion:output_type -> llm.CreateCompletionResponseChunk
	23, // 35: llm.LLM.CountTokens:output_type -> llm.CountTokensResponse
	25, // 36: llm.LLM.Models:output_type -> llm.ModelsResponse
	27, // 37: llm.LLM.GetModel:output_type -> llm.GetModelResponse
	34, // [34:38] is the sub-list for method output_type
	30, // [30:34] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_llmrpc_llm_proto_init() }
func file_llmrpc_llm_proto_init() {
	if File_llmrpc_llm_proto != nil {
		return
	}
	file_llmrpc_llm_proto_msgTypes[16].OneofWrappers = []any{
		(*CreateCompletionRequestChunk_Header)(nil),
		(*CreateCompletionRequestChunk_Message)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmrpc_llm_proto_rawDesc), len(file_llmrpc_llm_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llmrpc_llm_proto_goTypes,
		DependencyIndexes: file_llmrpc_llm_proto_depIdxs,
		EnumInfos:         file_llmrpc_llm_proto_enumTypes,
		MessageInfos:      file_llmrpc_llm_proto_msgTypes,
	}.Build()
	File_llmrpc_llm_proto = out.File
	file_llmrpc_llm_proto_goTypes = nil
	file_llmrpc_llm_proto_depIdxs = nil
}
