// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: syntaxrpc/syntax.proto

package syntaxrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Syntax_Search_FullMethodName = "/syntax.Syntax/Search"
)

// SyntaxClient is the client API for Syntax service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyntaxClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResponse], error)
}

type syntaxClient struct {
	cc grpc.ClientConnInterface
}

func NewSyntaxClient(cc grpc.ClientConnInterface) SyntaxClient {
	return &syntaxClient{cc}
}

func (c *syntaxClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Syntax_ServiceDesc.Streams[0], Syntax_Search_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, SearchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Syntax_SearchClient = grpc.ServerStreamingClient[SearchResponse]

// SyntaxServer is the server API for Syntax service.
// All implementations must embed UnimplementedSyntaxServer
// for forward compatibility.
type SyntaxServer interface {
	Search(*SearchRequest, grpc.ServerStreamingServer[SearchResponse]) error
	mustEmbedUnimplementedSyntaxServer()
}

// UnimplementedSyntaxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyntaxServer struct{}

func (UnimplementedSyntaxServer) Search(*SearchRequest, grpc.ServerStreamingServer[SearchResponse]) error {
	return status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSyntaxServer) mustEmbedUnimplementedSyntaxServer() {}
func (UnimplementedSyntaxServer) testEmbeddedByValue()                {}

// UnsafeSyntaxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyntaxServer will
// result in compilation errors.
type UnsafeSyntaxServer interface {
	mustEmbedUnimplementedSyntaxServer()
}

func RegisterSyntaxServer(s grpc.ServiceRegistrar, srv SyntaxServer) {
	// If the following call panics, it indicates UnimplementedSyntaxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Syntax_ServiceDesc, srv)
}

func _Syntax_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyntaxServer).Search(m, &grpc.GenericServerStream[SearchRequest, SearchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Syntax_SearchServer = grpc.ServerStreamingServer[SearchResponse]

// Syntax_ServiceDesc is the grpc.ServiceDesc for Syntax service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Syntax_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syntax.Syntax",
	HandlerType: (*SyntaxServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _Syntax_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "syntaxrpc/syntax.proto",
}
