// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: syntaxrpc/syntax.proto

package syntaxrpc

import (
	termrpc "github.com/unstablebuild/rune-go-sdk/term/termrpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	CaptureNames  []string               `protobuf:"bytes,2,rep,name=capture_names,json=captureNames,proto3" json:"capture_names,omitempty"`
	Languages     []string               `protobuf:"bytes,3,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetCaptureNames() []string {
	if x != nil {
		return x.CaptureNames
	}
	return nil
}

func (x *SearchRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

type SearchNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bitflags of node capture types to search for.
	// Values: Scope=1, DefinitionNamespace=2, Reference=4, DefinitionFunc=8,
	//
	//	DefinitionVar=16, DefinitionMethod=32, DefinitionType=64
	NodeTypes uint32 `protobuf:"varint,1,opt,name=node_types,json=nodeTypes,proto3" json:"node_types,omitempty"`
	// Optional language identifiers (e.g. "go", "python") that restrict the
	// search to files of those languages. Empty searches all languages.
	Languages     []string `protobuf:"bytes,2,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNodeRequest) Reset() {
	*x = SearchNodeRequest{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNodeRequest) ProtoMessage() {}

func (x *SearchNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNodeRequest.ProtoReflect.Descriptor instead.
func (*SearchNodeRequest) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{1}
}

func (x *SearchNodeRequest) GetNodeTypes() uint32 {
	if x != nil {
		return x.NodeTypes
	}
	return 0
}

func (x *SearchNodeRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	CaptureNames  []string               `protobuf:"bytes,3,rep,name=capture_names,json=captureNames,proto3" json:"capture_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetCaptureNames() []string {
	if x != nil {
		return x.CaptureNames
	}
	return nil
}

type QueryNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uri   string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// Bitflags of node capture types to search for.
	// Values: Scope=1, DefinitionNamespace=2, Reference=4, DefinitionFunc=8,
	//
	//	DefinitionVar=16, DefinitionMethod=32, DefinitionType=64
	NodeTypes     uint32 `protobuf:"varint,2,opt,name=node_types,json=nodeTypes,proto3" json:"node_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNodeRequest) Reset() {
	*x = QueryNodeRequest{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodeRequest) ProtoMessage() {}

func (x *QueryNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodeRequest.ProtoReflect.Descriptor instead.
func (*QueryNodeRequest) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{3}
}

func (x *QueryNodeRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *QueryNodeRequest) GetNodeTypes() uint32 {
	if x != nil {
		return x.NodeTypes
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	From          *termrpc.Coordinates   `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            *termrpc.Coordinates   `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	CaptureName   string                 `protobuf:"bytes,6,opt,name=capture_name,json=captureName,proto3" json:"capture_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *SearchResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchResponse) GetFrom() *termrpc.Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SearchResponse) GetTo() *termrpc.Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SearchResponse) GetCaptureName() string {
	if x != nil {
		return x.CaptureName
	}
	return ""
}

type HighlightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighlightRequest) Reset() {
	*x = HighlightRequest{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighlightRequest) ProtoMessage() {}

func (x *HighlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighlightRequest.ProtoReflect.Descriptor instead.
func (*HighlightRequest) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{5}
}

func (x *HighlightRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *HighlightRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type HighlightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *termrpc.Coordinates   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *termrpc.Coordinates   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Attr          *termrpc.Attributes    `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighlightResponse) Reset() {
	*x = HighlightResponse{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighlightResponse) ProtoMessage() {}

func (x *HighlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighlightResponse.ProtoReflect.Descriptor instead.
func (*HighlightResponse) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{6}
}

func (x *HighlightResponse) GetFrom() *termrpc.Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *HighlightResponse) GetTo() *termrpc.Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *HighlightResponse) GetAttr() *termrpc.Attributes {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *HighlightResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResolveSymbolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSymbolRequest) Reset() {
	*x = ResolveSymbolRequest{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSymbolRequest) ProtoMessage() {}

func (x *ResolveSymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSymbolRequest.ProtoReflect.Descriptor instead.
func (*ResolveSymbolRequest) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveSymbolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResolveSymbolMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uri   string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// 0-based line and character of the symbol.
	Line          uint32 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Character     uint32 `protobuf:"varint,3,opt,name=character,proto3" json:"character,omitempty"`
	Display       string `protobuf:"bytes,4,opt,name=display,proto3" json:"display,omitempty"`
	ImportPath    string `protobuf:"bytes,5,opt,name=import_path,json=importPath,proto3" json:"import_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSymbolMatch) Reset() {
	*x = ResolveSymbolMatch{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSymbolMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSymbolMatch) ProtoMessage() {}

func (x *ResolveSymbolMatch) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSymbolMatch.ProtoReflect.Descriptor instead.
func (*ResolveSymbolMatch) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveSymbolMatch) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ResolveSymbolMatch) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ResolveSymbolMatch) GetCharacter() uint32 {
	if x != nil {
		return x.Character
	}
	return 0
}

func (x *ResolveSymbolMatch) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *ResolveSymbolMatch) GetImportPath() string {
	if x != nil {
		return x.ImportPath
	}
	return ""
}

type ResolveSymbolProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Found         int64                  `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Step          int64                  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSymbolProgress) Reset() {
	*x = ResolveSymbolProgress{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSymbolProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSymbolProgress) ProtoMessage() {}

func (x *ResolveSymbolProgress) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSymbolProgress.ProtoReflect.Descriptor instead.
func (*ResolveSymbolProgress) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveSymbolProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResolveSymbolProgress) GetFound() int64 {
	if x != nil {
		return x.Found
	}
	return 0
}

func (x *ResolveSymbolProgress) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ResolveSymbolProgress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ResolveSymbolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ResolveSymbolResponse_Match
	//	*ResolveSymbolResponse_Progress
	Payload       isResolveSymbolResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSymbolResponse) Reset() {
	*x = ResolveSymbolResponse{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSymbolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSymbolResponse) ProtoMessage() {}

func (x *ResolveSymbolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSymbolResponse.ProtoReflect.Descriptor instead.
func (*ResolveSymbolResponse) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveSymbolResponse) GetPayload() isResolveSymbolResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ResolveSymbolResponse) GetMatch() *ResolveSymbolMatch {
	if x != nil {
		if x, ok := x.Payload.(*ResolveSymbolResponse_Match); ok {
			return x.Match
		}
	}
	return nil
}

func (x *ResolveSymbolResponse) GetProgress() *ResolveSymbolProgress {
	if x != nil {
		if x, ok := x.Payload.(*ResolveSymbolResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isResolveSymbolResponse_Payload interface {
	isResolveSymbolResponse_Payload()
}

type ResolveSymbolResponse_Match struct {
	Match *ResolveSymbolMatch `protobuf:"bytes,1,opt,name=match,proto3,oneof"`
}

type ResolveSymbolResponse_Progress struct {
	Progress *ResolveSymbolProgress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

func (*ResolveSymbolResponse_Match) isResolveSymbolResponse_Payload() {}

func (*ResolveSymbolResponse_Progress) isResolveSymbolResponse_Payload() {}

type ListReferencedSymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReferencedSymbolsRequest) Reset() {
	*x = ListReferencedSymbolsRequest{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReferencedSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferencedSymbolsRequest) ProtoMessage() {}

func (x *ListReferencedSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferencedSymbolsRequest.ProtoReflect.Descriptor instead.
func (*ListReferencedSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{11}
}

type ListReferencedSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReferencedSymbolsResponse) Reset() {
	*x = ListReferencedSymbolsResponse{}
	mi := &file_syntaxrpc_syntax_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReferencedSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferencedSymbolsResponse) ProtoMessage() {}

func (x *ListReferencedSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syntaxrpc_syntax_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferencedSymbolsResponse.ProtoReflect.Descriptor instead.
func (*ListReferencedSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_syntaxrpc_syntax_proto_rawDescGZIP(), []int{12}
}

func (x *ListReferencedSymbolsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_syntaxrpc_syntax_proto protoreflect.FileDescriptor

const file_syntaxrpc_syntax_proto_rawDesc = "" +
	"\n" +
	"\x16syntaxrpc/syntax.proto\x12\x06syntax\x1a\x17term/termrpc/term.proto\"h\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12#\n" +
	"\rcapture_names\x18\x02 \x03(\tR\fcaptureNames\x12\x1c\n" +
	"\tlanguages\x18\x03 \x03(\tR\tlanguages\"P\n" +
	"\x11SearchNodeRequest\x12\x1d\n" +
	"\n" +
	"node_types\x18\x01 \x01(\rR\tnodeTypes\x12\x1c\n" +
	"\tlanguages\x18\x02 \x03(\tR\tlanguages\"[\n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12#\n" +
	"\rcapture_names\x18\x03 \x03(\tR\fcaptureNames\"C\n" +
	"\x10QueryNodeRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"node_types\x18\x02 \x01(\rR\tnodeTypes\"\xa9\x01\n" +
	"\x0eSearchResponse\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12%\n" +
	"\x04from\x18\x04 \x01(\v2\x11.term.CoordinatesR\x04from\x12!\n" +
	"\x02to\x18\x05 \x01(\v2\x11.term.CoordinatesR\x02to\x12!\n" +
	"\fcapture_name\x18\x06 \x01(\tR\vcaptureNameJ\x04\b\x03\x10\x04\">\n" +
	"\x10HighlightRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x9d\x01\n" +
	"\x11HighlightResponse\x12%\n" +
	"\x04from\x18\x01 \x01(\v2\x11.term.CoordinatesR\x04from\x12!\n" +
	"\x02to\x18\x02 \x01(\v2\x11.term.CoordinatesR\x02to\x12$\n" +
	"\x04attr\x18\x03 \x01(\v2\x10.term.AttributesR\x04attr\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"*\n" +
	"\x14ResolveSymbolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x93\x01\n" +
	"\x12ResolveSymbolMatch\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x12\n" +
	"\x04line\x18\x02 \x01(\rR\x04line\x12\x1c\n" +
	"\tcharacter\x18\x03 \x01(\rR\tcharacter\x12\x18\n" +
	"\adisplay\x18\x04 \x01(\tR\adisplay\x12\x1f\n" +
	"\vimport_path\x18\x05 \x01(\tR\n" +
	"importPath\"q\n" +
	"\x15ResolveSymbolProgress\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05found\x18\x02 \x01(\x03R\x05found\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x03R\x04step\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"\x93\x01\n" +
	"\x15ResolveSymbolResponse\x122\n" +
	"\x05match\x18\x01 \x01(\v2\x1a.syntax.ResolveSymbolMatchH\x00R\x05match\x12;\n" +
	"\bprogress\x18\x02 \x01(\v2\x1d.syntax.ResolveSymbolProgressH\x00R\bprogressB\t\n" +
	"\apayload\"\x1e\n" +
	"\x1cListReferencedSymbolsRequest\"3\n" +
	"\x1dListReferencedSymbolsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xfc\x03\n" +
	"\x06Syntax\x129\n" +
	"\x06Search\x12\x15.syntax.SearchRequest\x1a\x16.syntax.SearchResponse0\x01\x12A\n" +
	"\n" +
	"SearchNode\x12\x19.syntax.SearchNodeRequest\x1a\x16.syntax.SearchResponse0\x01\x127\n" +
	"\x05Query\x12\x14.syntax.QueryRequest\x1a\x16.syntax.SearchResponse0\x01\x12?\n" +
	"\tQueryNode\x12\x18.syntax.QueryNodeRequest\x1a\x16.syntax.SearchResponse0\x01\x12B\n" +
	"\tHighlight\x12\x18.syntax.HighlightRequest\x1a\x19.syntax.HighlightResponse0\x01\x12N\n" +
	"\rResolveSymbol\x12\x1c.syntax.ResolveSymbolRequest\x1a\x1d.syntax.ResolveSymbolResponse0\x01\x12f\n" +
	"\x15ListReferencedSymbols\x12$.syntax.ListReferencedSymbolsRequest\x1a%.syntax.ListReferencedSymbolsResponse0\x01B>Z<github.com/unstablebuild/rune-go-sdk/api/syntaxapi/syntaxrpcb\x06proto3"

var (
	file_syntaxrpc_syntax_proto_rawDescOnce sync.Once
	file_syntaxrpc_syntax_proto_rawDescData []byte
)

func file_syntaxrpc_syntax_proto_rawDescGZIP() []byte {
	file_syntaxrpc_syntax_proto_rawDescOnce.Do(func() {
		file_syntaxrpc_syntax_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_syntaxrpc_syntax_proto_rawDesc), len(file_syntaxrpc_syntax_proto_rawDesc)))
	})
	return file_syntaxrpc_syntax_proto_rawDescData
}

var file_syntaxrpc_syntax_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_syntaxrpc_syntax_proto_goTypes = []any{
	(*SearchRequest)(nil),                 // 0: syntax.SearchRequest
	(*SearchNodeRequest)(nil),             // 1: syntax.SearchNodeRequest
	(*QueryRequest)(nil),                  // 2: syntax.QueryRequest
	(*QueryNodeRequest)(nil),              // 3: syntax.QueryNodeRequest
	(*SearchResponse)(nil),                // 4: syntax.SearchResponse
	(*HighlightRequest)(nil),              // 5: syntax.HighlightRequest
	(*HighlightResponse)(nil),             // 6: syntax.HighlightResponse
	(*ResolveSymbolRequest)(nil),          // 7: syntax.ResolveSymbolRequest
	(*ResolveSymbolMatch)(nil),            // 8: syntax.ResolveSymbolMatch
	(*ResolveSymbolProgress)(nil),         // 9: syntax.ResolveSymbolProgress
	(*ResolveSymbolResponse)(nil),         // 10: syntax.ResolveSymbolResponse
	(*ListReferencedSymbolsRequest)(nil),  // 11: syntax.ListReferencedSymbolsRequest
	(*ListReferencedSymbolsResponse)(nil), // 12: syntax.ListReferencedSymbolsResponse
	(*termrpc.Coordinates)(nil),           // 13: term.Coordinates
	(*termrpc.Attributes)(nil),            // 14: term.Attributes
}
var file_syntaxrpc_syntax_proto_depIdxs = []int32{
	13, // 0: syntax.SearchResponse.from:type_name -> term.Coordinates
	13, // 1: syntax.SearchResponse.to:type_name -> term.Coordinates
	13, // 2: syntax.HighlightResponse.from:type_name -> term.Coordinates
	13, // 3: syntax.HighlightResponse.to:type_name -> term.Coordinates
	14, // 4: syntax.HighlightResponse.attr:type_name -> term.Attributes
	8,  // 5: syntax.ResolveSymbolResponse.match:type_name -> syntax.ResolveSymbolMatch
	9,  // 6: syntax.ResolveSymbolResponse.progress:type_name -> syntax.ResolveSymbolProgress
	0,  // 7: syntax.Syntax.Search:input_type -> syntax.SearchRequest
	1,  // 8: syntax.Syntax.SearchNode:input_type -> syntax.SearchNodeRequest
	2,  // 9: syntax.Syntax.Query:input_type -> syntax.QueryRequest
	3,  // 10: syntax.Syntax.QueryNode:input_type -> syntax.QueryNodeRequest
	5,  // 11: syntax.Syntax.Highlight:input_type -> syntax.HighlightRequest
	7,  // 12: syntax.Syntax.ResolveSymbol:input_type -> syntax.ResolveSymbolRequest
	11, // 13: syntax.Syntax.ListReferencedSymbols:input_type -> syntax.ListReferencedSymbolsRequest
	4,  // 14: syntax.Syntax.Search:output_type -> syntax.SearchResponse
	4,  // 15: syntax.Syntax.SearchNode:output_type -> syntax.SearchResponse
	4,  // 16: syntax.Syntax.Query:output_type -> syntax.SearchResponse
	4,  // 17: syntax.Syntax.QueryNode:output_type -> syntax.SearchResponse
	6,  // 18: syntax.Syntax.Highlight:output_type -> syntax.HighlightResponse
	10, // 19: syntax.Syntax.ResolveSymbol:output_type -> syntax.ResolveSymbolResponse
	12, // 20: syntax.Syntax.ListReferencedSymbols:output_type -> syntax.ListReferencedSymbolsResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_syntaxrpc_syntax_proto_init() }
func file_syntaxrpc_syntax_proto_init() {
	if File_syntaxrpc_syntax_proto != nil {
		return
	}
	file_syntaxrpc_syntax_proto_msgTypes[10].OneofWrappers = []any{
		(*ResolveSymbolResponse_Match)(nil),
		(*ResolveSymbolResponse_Progress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_syntaxrpc_syntax_proto_rawDesc), len(file_syntaxrpc_syntax_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_syntaxrpc_syntax_proto_goTypes,
		DependencyIndexes: file_syntaxrpc_syntax_proto_depIdxs,
		MessageInfos:      file_syntaxrpc_syntax_proto_msgTypes,
	}.Build()
	File_syntaxrpc_syntax_proto = out.File
	file_syntaxrpc_syntax_proto_goTypes = nil
	file_syntaxrpc_syntax_proto_depIdxs = nil
}
