// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: browserrpc/browser.proto

package browserrpc

import (
	handlerrpc "github.com/unstablebuild/rune-go-sdk/handler/handlerrpc"
	termrpc "github.com/unstablebuild/rune-go-sdk/term/termrpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Orientation int32

const (
	Orientation_Default Orientation = 0
	Orientation_Top     Orientation = 1
	Orientation_Bottom  Orientation = 2
	Orientation_Left    Orientation = 3
	Orientation_Right   Orientation = 4
)

// Enum value maps for Orientation.
var (
	Orientation_name = map[int32]string{
		0: "Default",
		1: "Top",
		2: "Bottom",
		3: "Left",
		4: "Right",
	}
	Orientation_value = map[string]int32{
		"Default": 0,
		"Top":     1,
		"Bottom":  2,
		"Left":    3,
		"Right":   4,
	}
)

func (x Orientation) Enum() *Orientation {
	p := new(Orientation)
	*p = x
	return p
}

func (x Orientation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Orientation) Descriptor() protoreflect.EnumDescriptor {
	return file_browserrpc_browser_proto_enumTypes[0].Descriptor()
}

func (Orientation) Type() protoreflect.EnumType {
	return &file_browserrpc_browser_proto_enumTypes[0]
}

func (x Orientation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Orientation.Descriptor instead.
func (Orientation) EnumDescriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{0}
}

type BarRequest_Frame int32

const (
	BarRequest_Default BarRequest_Frame = 0
	BarRequest_Always  BarRequest_Frame = 1
	BarRequest_Never   BarRequest_Frame = 2
)

// Enum value maps for BarRequest_Frame.
var (
	BarRequest_Frame_name = map[int32]string{
		0: "Default",
		1: "Always",
		2: "Never",
	}
	BarRequest_Frame_value = map[string]int32{
		"Default": 0,
		"Always":  1,
		"Never":   2,
	}
)

func (x BarRequest_Frame) Enum() *BarRequest_Frame {
	p := new(BarRequest_Frame)
	*p = x
	return p
}

func (x BarRequest_Frame) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BarRequest_Frame) Descriptor() protoreflect.EnumDescriptor {
	return file_browserrpc_browser_proto_enumTypes[1].Descriptor()
}

func (BarRequest_Frame) Type() protoreflect.EnumType {
	return &file_browserrpc_browser_proto_enumTypes[1]
}

func (x BarRequest_Frame) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BarRequest_Frame.Descriptor instead.
func (BarRequest_Frame) EnumDescriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{8, 0}
}

type OpenResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResourceRequest) Reset() {
	*x = OpenResourceRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResourceRequest) ProtoMessage() {}

func (x *OpenResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResourceRequest.ProtoReflect.Descriptor instead.
func (*OpenResourceRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{0}
}

func (x *OpenResourceRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type OpenResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResourceResponse) Reset() {
	*x = OpenResourceResponse{}
	mi := &file_browserrpc_browser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResourceResponse) ProtoMessage() {}

func (x *OpenResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResourceResponse.ProtoReflect.Descriptor instead.
func (*OpenResourceResponse) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResourceResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Level         uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NotifyRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_browserrpc_browser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateNotificationProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Progress      int64                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationProgressRequest) Reset() {
	*x = UpdateNotificationProgressRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationProgressRequest) ProtoMessage() {}

func (x *UpdateNotificationProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationProgressRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNotificationProgressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNotificationProgressRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UpdateNotificationProgressRequest) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *UpdateNotificationProgressRequest) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateNotificationProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationProgressResponse) Reset() {
	*x = UpdateNotificationProgressResponse{}
	mi := &file_browserrpc_browser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationProgressResponse) ProtoMessage() {}

func (x *UpdateNotificationProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationProgressResponse) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{5}
}

type Mapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *termrpc.Event         `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *termrpc.Event         `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mapping) Reset() {
	*x = Mapping{}
	mi := &file_browserrpc_browser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mapping) ProtoMessage() {}

func (x *Mapping) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mapping.ProtoReflect.Descriptor instead.
func (*Mapping) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{6}
}

func (x *Mapping) GetFrom() *termrpc.Event {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Mapping) GetTo() *termrpc.Event {
	if x != nil {
		return x.To
	}
	return nil
}

type SplitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Orientation   Orientation            `protobuf:"varint,2,opt,name=orientation,proto3,enum=browser.Orientation" json:"orientation,omitempty"`
	WindowId      uint64                 `protobuf:"varint,3,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitRequest) Reset() {
	*x = SplitRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitRequest) ProtoMessage() {}

func (x *SplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitRequest.ProtoReflect.Descriptor instead.
func (*SplitRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{7}
}

func (x *SplitRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *SplitRequest) GetOrientation() Orientation {
	if x != nil {
		return x.Orientation
	}
	return Orientation_Default
}

func (x *SplitRequest) GetWindowId() uint64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

type BarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orientation   Orientation            `protobuf:"varint,1,opt,name=orientation,proto3,enum=browser.Orientation" json:"orientation,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Frame         BarRequest_Frame       `protobuf:"varint,3,opt,name=frame,proto3,enum=browser.BarRequest_Frame" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarRequest) Reset() {
	*x = BarRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarRequest) ProtoMessage() {}

func (x *BarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarRequest.ProtoReflect.Descriptor instead.
func (*BarRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{8}
}

func (x *BarRequest) GetOrientation() Orientation {
	if x != nil {
		return x.Orientation
	}
	return Orientation_Default
}

func (x *BarRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BarRequest) GetFrame() BarRequest_Frame {
	if x != nil {
		return x.Frame
	}
	return BarRequest_Default
}

type FloatingWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        *termrpc.Coordinates   `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Alignment     uint32                 `protobuf:"varint,2,opt,name=alignment,proto3" json:"alignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatingWindowRequest) Reset() {
	*x = FloatingWindowRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatingWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatingWindowRequest) ProtoMessage() {}

func (x *FloatingWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatingWindowRequest.ProtoReflect.Descriptor instead.
func (*FloatingWindowRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{9}
}

func (x *FloatingWindowRequest) GetOffset() *termrpc.Coordinates {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *FloatingWindowRequest) GetAlignment() uint32 {
	if x != nil {
		return x.Alignment
	}
	return 0
}

type TabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName  string                 `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceIcon  string                 `protobuf:"bytes,3,opt,name=resource_icon,json=resourceIcon,proto3" json:"resource_icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabRequest) Reset() {
	*x = TabRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabRequest) ProtoMessage() {}

func (x *TabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabRequest.ProtoReflect.Descriptor instead.
func (*TabRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{10}
}

func (x *TabRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *TabRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *TabRequest) GetResourceIcon() string {
	if x != nil {
		return x.ResourceIcon
	}
	return ""
}

type FocusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FocusRequest) Reset() {
	*x = FocusRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusRequest) ProtoMessage() {}

func (x *FocusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusRequest.ProtoReflect.Descriptor instead.
func (*FocusRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{11}
}

type FocusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      uint64                 `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FocusResponse) Reset() {
	*x = FocusResponse{}
	mi := &file_browserrpc_browser_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusResponse) ProtoMessage() {}

func (x *FocusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusResponse.ProtoReflect.Descriptor instead.
func (*FocusResponse) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{12}
}

func (x *FocusResponse) GetWindowId() uint64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ev            *termrpc.Event         `protobuf:"bytes,1,opt,name=ev,proto3" json:"ev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{13}
}

func (x *PublishRequest) GetEv() *termrpc.Event {
	if x != nil {
		return x.Ev
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_browserrpc_browser_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{14}
}

type WindowCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      uint64                 `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowCloseRequest) Reset() {
	*x = WindowCloseRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowCloseRequest) ProtoMessage() {}

func (x *WindowCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowCloseRequest.ProtoReflect.Descriptor instead.
func (*WindowCloseRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{15}
}

func (x *WindowCloseRequest) GetWindowId() uint64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

type WindowCloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowCloseResponse) Reset() {
	*x = WindowCloseResponse{}
	mi := &file_browserrpc_browser_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowCloseResponse) ProtoMessage() {}

func (x *WindowCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowCloseResponse.ProtoReflect.Descriptor instead.
func (*WindowCloseResponse) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{16}
}

type WindowSetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      uint64                 `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowSetContentRequest) Reset() {
	*x = WindowSetContentRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowSetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowSetContentRequest) ProtoMessage() {}

func (x *WindowSetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowSetContentRequest.ProtoReflect.Descriptor instead.
func (*WindowSetContentRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{17}
}

func (x *WindowSetContentRequest) GetWindowId() uint64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

func (x *WindowSetContentRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type DimensionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DimensionsRequest) Reset() {
	*x = DimensionsRequest{}
	mi := &file_browserrpc_browser_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DimensionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DimensionsRequest) ProtoMessage() {}

func (x *DimensionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DimensionsRequest.ProtoReflect.Descriptor instead.
func (*DimensionsRequest) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{18}
}

type DimensionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DimensionsResponse) Reset() {
	*x = DimensionsResponse{}
	mi := &file_browserrpc_browser_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DimensionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DimensionsResponse) ProtoMessage() {}

func (x *DimensionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DimensionsResponse.ProtoReflect.Descriptor instead.
func (*DimensionsResponse) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{19}
}

func (x *DimensionsResponse) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DimensionsResponse) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type FloatingWindowMessage struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          handlerrpc.MessageType               `protobuf:"varint,1,opt,name=type,proto3,enum=handler.MessageType" json:"type,omitempty"`
	Draw          *handlerrpc.DrawStreamResponse       `protobuf:"bytes,2,opt,name=draw,proto3" json:"draw,omitempty"`
	Handle        *handlerrpc.HandleStreamResponse     `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Close         *handlerrpc.CloseStreamResponse      `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	Cursor        *handlerrpc.CursorStreamResponse     `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Selection     *handlerrpc.SelectionStreamResponse  `protobuf:"bytes,7,opt,name=selection,proto3" json:"selection,omitempty"`
	Dimensions    *handlerrpc.DimensionsStreamResponse `protobuf:"bytes,8,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Request       *FloatingWindowRequest               `protobuf:"bytes,10,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatingWindowMessage) Reset() {
	*x = FloatingWindowMessage{}
	mi := &file_browserrpc_browser_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatingWindowMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatingWindowMessage) ProtoMessage() {}

func (x *FloatingWindowMessage) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatingWindowMessage.ProtoReflect.Descriptor instead.
func (*FloatingWindowMessage) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{20}
}

func (x *FloatingWindowMessage) GetType() handlerrpc.MessageType {
	if x != nil {
		return x.Type
	}
	return handlerrpc.MessageType(0)
}

func (x *FloatingWindowMessage) GetDraw() *handlerrpc.DrawStreamResponse {
	if x != nil {
		return x.Draw
	}
	return nil
}

func (x *FloatingWindowMessage) GetHandle() *handlerrpc.HandleStreamResponse {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *FloatingWindowMessage) GetClose() *handlerrpc.CloseStreamResponse {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *FloatingWindowMessage) GetCursor() *handlerrpc.CursorStreamResponse {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *FloatingWindowMessage) GetSelection() *handlerrpc.SelectionStreamResponse {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *FloatingWindowMessage) GetDimensions() *handlerrpc.DimensionsStreamResponse {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *FloatingWindowMessage) GetRequest() *FloatingWindowRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type SplitWindowMessage struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          handlerrpc.MessageType               `protobuf:"varint,1,opt,name=type,proto3,enum=handler.MessageType" json:"type,omitempty"`
	Draw          *handlerrpc.DrawStreamResponse       `protobuf:"bytes,2,opt,name=draw,proto3" json:"draw,omitempty"`
	Handle        *handlerrpc.HandleStreamResponse     `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Close         *handlerrpc.CloseStreamResponse      `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	Cursor        *handlerrpc.CursorStreamResponse     `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Selection     *handlerrpc.SelectionStreamResponse  `protobuf:"bytes,7,opt,name=selection,proto3" json:"selection,omitempty"`
	Dimensions    *handlerrpc.DimensionsStreamResponse `protobuf:"bytes,8,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Request       *SplitRequest                        `protobuf:"bytes,10,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitWindowMessage) Reset() {
	*x = SplitWindowMessage{}
	mi := &file_browserrpc_browser_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitWindowMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitWindowMessage) ProtoMessage() {}

func (x *SplitWindowMessage) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitWindowMessage.ProtoReflect.Descriptor instead.
func (*SplitWindowMessage) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{21}
}

func (x *SplitWindowMessage) GetType() handlerrpc.MessageType {
	if x != nil {
		return x.Type
	}
	return handlerrpc.MessageType(0)
}

func (x *SplitWindowMessage) GetDraw() *handlerrpc.DrawStreamResponse {
	if x != nil {
		return x.Draw
	}
	return nil
}

func (x *SplitWindowMessage) GetHandle() *handlerrpc.HandleStreamResponse {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *SplitWindowMessage) GetClose() *handlerrpc.CloseStreamResponse {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *SplitWindowMessage) GetCursor() *handlerrpc.CursorStreamResponse {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *SplitWindowMessage) GetSelection() *handlerrpc.SelectionStreamResponse {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *SplitWindowMessage) GetDimensions() *handlerrpc.DimensionsStreamResponse {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *SplitWindowMessage) GetRequest() *SplitRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type BarMessage struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          handlerrpc.MessageType               `protobuf:"varint,1,opt,name=type,proto3,enum=handler.MessageType" json:"type,omitempty"`
	Draw          *handlerrpc.DrawStreamResponse       `protobuf:"bytes,2,opt,name=draw,proto3" json:"draw,omitempty"`
	Handle        *handlerrpc.HandleStreamResponse     `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Close         *handlerrpc.CloseStreamResponse      `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	Cursor        *handlerrpc.CursorStreamResponse     `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Selection     *handlerrpc.SelectionStreamResponse  `protobuf:"bytes,7,opt,name=selection,proto3" json:"selection,omitempty"`
	Dimensions    *handlerrpc.DimensionsStreamResponse `protobuf:"bytes,8,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Request       *BarRequest                          `protobuf:"bytes,10,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarMessage) Reset() {
	*x = BarMessage{}
	mi := &file_browserrpc_browser_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarMessage) ProtoMessage() {}

func (x *BarMessage) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarMessage.ProtoReflect.Descriptor instead.
func (*BarMessage) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{22}
}

func (x *BarMessage) GetType() handlerrpc.MessageType {
	if x != nil {
		return x.Type
	}
	return handlerrpc.MessageType(0)
}

func (x *BarMessage) GetDraw() *handlerrpc.DrawStreamResponse {
	if x != nil {
		return x.Draw
	}
	return nil
}

func (x *BarMessage) GetHandle() *handlerrpc.HandleStreamResponse {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *BarMessage) GetClose() *handlerrpc.CloseStreamResponse {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *BarMessage) GetCursor() *handlerrpc.CursorStreamResponse {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *BarMessage) GetSelection() *handlerrpc.SelectionStreamResponse {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *BarMessage) GetDimensions() *handlerrpc.DimensionsStreamResponse {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *BarMessage) GetRequest() *BarRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type WindowSetContentMessage struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          handlerrpc.MessageType               `protobuf:"varint,1,opt,name=type,proto3,enum=handler.MessageType" json:"type,omitempty"`
	Draw          *handlerrpc.DrawStreamResponse       `protobuf:"bytes,2,opt,name=draw,proto3" json:"draw,omitempty"`
	Handle        *handlerrpc.HandleStreamResponse     `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Close         *handlerrpc.CloseStreamResponse      `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	Cursor        *handlerrpc.CursorStreamResponse     `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Selection     *handlerrpc.SelectionStreamResponse  `protobuf:"bytes,7,opt,name=selection,proto3" json:"selection,omitempty"`
	Dimensions    *handlerrpc.DimensionsStreamResponse `protobuf:"bytes,8,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Request       *WindowSetContentRequest             `protobuf:"bytes,10,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowSetContentMessage) Reset() {
	*x = WindowSetContentMessage{}
	mi := &file_browserrpc_browser_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowSetContentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowSetContentMessage) ProtoMessage() {}

func (x *WindowSetContentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowSetContentMessage.ProtoReflect.Descriptor instead.
func (*WindowSetContentMessage) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{23}
}

func (x *WindowSetContentMessage) GetType() handlerrpc.MessageType {
	if x != nil {
		return x.Type
	}
	return handlerrpc.MessageType(0)
}

func (x *WindowSetContentMessage) GetDraw() *handlerrpc.DrawStreamResponse {
	if x != nil {
		return x.Draw
	}
	return nil
}

func (x *WindowSetContentMessage) GetHandle() *handlerrpc.HandleStreamResponse {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *WindowSetContentMessage) GetClose() *handlerrpc.CloseStreamResponse {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *WindowSetContentMessage) GetCursor() *handlerrpc.CursorStreamResponse {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *WindowSetContentMessage) GetSelection() *handlerrpc.SelectionStreamResponse {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *WindowSetContentMessage) GetDimensions() *handlerrpc.DimensionsStreamResponse {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *WindowSetContentMessage) GetRequest() *WindowSetContentRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type TabMessage struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          handlerrpc.MessageType               `protobuf:"varint,1,opt,name=type,proto3,enum=handler.MessageType" json:"type,omitempty"`
	Draw          *handlerrpc.DrawStreamResponse       `protobuf:"bytes,2,opt,name=draw,proto3" json:"draw,omitempty"`
	Handle        *handlerrpc.HandleStreamResponse     `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Close         *handlerrpc.CloseStreamResponse      `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	Cursor        *handlerrpc.CursorStreamResponse     `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Selection     *handlerrpc.SelectionStreamResponse  `protobuf:"bytes,7,opt,name=selection,proto3" json:"selection,omitempty"`
	Dimensions    *handlerrpc.DimensionsStreamResponse `protobuf:"bytes,8,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Request       *TabRequest                          `protobuf:"bytes,10,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabMessage) Reset() {
	*x = TabMessage{}
	mi := &file_browserrpc_browser_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabMessage) ProtoMessage() {}

func (x *TabMessage) ProtoReflect() protoreflect.Message {
	mi := &file_browserrpc_browser_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabMessage.ProtoReflect.Descriptor instead.
func (*TabMessage) Descriptor() ([]byte, []int) {
	return file_browserrpc_browser_proto_rawDescGZIP(), []int{24}
}

func (x *TabMessage) GetType() handlerrpc.MessageType {
	if x != nil {
		return x.Type
	}
	return handlerrpc.MessageType(0)
}

func (x *TabMessage) GetDraw() *handlerrpc.DrawStreamResponse {
	if x != nil {
		return x.Draw
	}
	return nil
}

func (x *TabMessage) GetHandle() *handlerrpc.HandleStreamResponse {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *TabMessage) GetClose() *handlerrpc.CloseStreamResponse {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *TabMessage) GetCursor() *handlerrpc.CursorStreamResponse {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *TabMessage) GetSelection() *handlerrpc.SelectionStreamResponse {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *TabMessage) GetDimensions() *handlerrpc.DimensionsStreamResponse {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *TabMessage) GetRequest() *TabRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

var File_browserrpc_browser_proto protoreflect.FileDescriptor

const file_browserrpc_browser_proto_rawDesc = "" +
	"\n" +
	"\x18browserrpc/browser.proto\x12\abrowser\x1a\x17term/termrpc/term.proto\x1a handler/handlerrpc/handler.proto\"1\n" +
	"\x13OpenResourceRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\"(\n" +
	"\x14OpenResourceResponse\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"7\n" +
	"\rNotifyRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\" \n" +
	"\x0eNotifyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"!UpdateNotificationProgressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x03R\bprogress\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"$\n" +
	"\"UpdateNotificationProgressResponse\"G\n" +
	"\aMapping\x12\x1f\n" +
	"\x04from\x18\x01 \x01(\v2\v.term.EventR\x04from\x12\x1b\n" +
	"\x02to\x18\x02 \x01(\v2\v.term.EventR\x02to\"u\n" +
	"\fSplitRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x126\n" +
	"\vorientation\x18\x02 \x01(\x0e2\x14.browser.OrientationR\vorientation\x12\x1b\n" +
	"\twindow_id\x18\x03 \x01(\x04R\bwindowId\"\xb6\x01\n" +
	"\n" +
	"BarRequest\x126\n" +
	"\vorientation\x18\x01 \x01(\x0e2\x14.browser.OrientationR\vorientation\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12/\n" +
	"\x05frame\x18\x03 \x01(\x0e2\x19.browser.BarRequest.FrameR\x05frame\"+\n" +
	"\x05Frame\x12\v\n" +
	"\aDefault\x10\x00\x12\n" +
	"\n" +
	"\x06Always\x10\x01\x12\t\n" +
	"\x05Never\x10\x02\"`\n" +
	"\x15FloatingWindowRequest\x12)\n" +
	"\x06offset\x18\x01 \x01(\v2\x11.term.CoordinatesR\x06offset\x12\x1c\n" +
	"\talignment\x18\x02 \x01(\rR\talignment\"w\n" +
	"\n" +
	"TabRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\x02 \x01(\tR\fresourceName\x12#\n" +
	"\rresource_icon\x18\x03 \x01(\tR\fresourceIcon\"\x0e\n" +
	"\fFocusRequest\",\n" +
	"\rFocusResponse\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\x04R\bwindowId\"-\n" +
	"\x0ePublishRequest\x12\x1b\n" +
	"\x02ev\x18\x01 \x01(\v2\v.term.EventR\x02ev\"\x11\n" +
	"\x0fPublishResponse\"1\n" +
	"\x12WindowCloseRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\x04R\bwindowId\"\x15\n" +
	"\x13WindowCloseResponse\"H\n" +
	"\x17WindowSetContentRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\x04R\bwindowId\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\"\x13\n" +
	"\x11DimensionsRequest\"B\n" +
	"\x12DimensionsResponse\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"\xd1\x03\n" +
	"\x15FloatingWindowMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.handler.MessageTypeR\x04type\x12/\n" +
	"\x04draw\x18\x02 \x01(\v2\x1b.handler.DrawStreamResponseR\x04draw\x125\n" +
	"\x06handle\x18\x03 \x01(\v2\x1d.handler.HandleStreamResponseR\x06handle\x122\n" +
	"\x05close\x18\x05 \x01(\v2\x1c.handler.CloseStreamResponseR\x05close\x125\n" +
	"\x06cursor\x18\x06 \x01(\v2\x1d.handler.CursorStreamResponseR\x06cursor\x12>\n" +
	"\tselection\x18\a \x01(\v2 .handler.SelectionStreamResponseR\tselection\x12A\n" +
	"\n" +
	"dimensions\x18\b \x01(\v2!.handler.DimensionsStreamResponseR\n" +
	"dimensions\x128\n" +
	"\arequest\x18\n" +
	" \x01(\v2\x1e.browser.FloatingWindowRequestR\arequest\"\xc5\x03\n" +
	"\x12SplitWindowMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.handler.MessageTypeR\x04type\x12/\n" +
	"\x04draw\x18\x02 \x01(\v2\x1b.handler.DrawStreamResponseR\x04draw\x125\n" +
	"\x06handle\x18\x03 \x01(\v2\x1d.handler.HandleStreamResponseR\x06handle\x122\n" +
	"\x05close\x18\x05 \x01(\v2\x1c.handler.CloseStreamResponseR\x05close\x125\n" +
	"\x06cursor\x18\x06 \x01(\v2\x1d.handler.CursorStreamResponseR\x06cursor\x12>\n" +
	"\tselection\x18\a \x01(\v2 .handler.SelectionStreamResponseR\tselection\x12A\n" +
	"\n" +
	"dimensions\x18\b \x01(\v2!.handler.DimensionsStreamResponseR\n" +
	"dimensions\x12/\n" +
	"\arequest\x18\n" +
	" \x01(\v2\x15.browser.SplitRequestR\arequest\"\xbb\x03\n" +
	"\n" +
	"BarMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.handler.MessageTypeR\x04type\x12/\n" +
	"\x04draw\x18\x02 \x01(\v2\x1b.handler.DrawStreamResponseR\x04draw\x125\n" +
	"\x06handle\x18\x03 \x01(\v2\x1d.handler.HandleStreamResponseR\x06handle\x122\n" +
	"\x05close\x18\x05 \x01(\v2\x1c.handler.CloseStreamResponseR\x05close\x125\n" +
	"\x06cursor\x18\x06 \x01(\v2\x1d.handler.CursorStreamResponseR\x06cursor\x12>\n" +
	"\tselection\x18\a \x01(\v2 .handler.SelectionStreamResponseR\tselection\x12A\n" +
	"\n" +
	"dimensions\x18\b \x01(\v2!.handler.DimensionsStreamResponseR\n" +
	"dimensions\x12-\n" +
	"\arequest\x18\n" +
	" \x01(\v2\x13.browser.BarRequestR\arequest\"\xd5\x03\n" +
	"\x17WindowSetContentMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.handler.MessageTypeR\x04type\x12/\n" +
	"\x04draw\x18\x02 \x01(\v2\x1b.handler.DrawStreamResponseR\x04draw\x125\n" +
	"\x06handle\x18\x03 \x01(\v2\x1d.handler.HandleStreamResponseR\x06handle\x122\n" +
	"\x05close\x18\x05 \x01(\v2\x1c.handler.CloseStreamResponseR\x05close\x125\n" +
	"\x06cursor\x18\x06 \x01(\v2\x1d.handler.CursorStreamResponseR\x06cursor\x12>\n" +
	"\tselection\x18\a \x01(\v2 .handler.SelectionStreamResponseR\tselection\x12A\n" +
	"\n" +
	"dimensions\x18\b \x01(\v2!.handler.DimensionsStreamResponseR\n" +
	"dimensions\x12:\n" +
	"\arequest\x18\n" +
	" \x01(\v2 .browser.WindowSetContentRequestR\arequest\"\xbb\x03\n" +
	"\n" +
	"TabMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.handler.MessageTypeR\x04type\x12/\n" +
	"\x04draw\x18\x02 \x01(\v2\x1b.handler.DrawStreamResponseR\x04draw\x125\n" +
	"\x06handle\x18\x03 \x01(\v2\x1d.handler.HandleStreamResponseR\x06handle\x122\n" +
	"\x05close\x18\x05 \x01(\v2\x1c.handler.CloseStreamResponseR\x05close\x125\n" +
	"\x06cursor\x18\x06 \x01(\v2\x1d.handler.CursorStreamResponseR\x06cursor\x12>\n" +
	"\tselection\x18\a \x01(\v2 .handler.SelectionStreamResponseR\tselection\x12A\n" +
	"\n" +
	"dimensions\x18\b \x01(\v2!.handler.DimensionsStreamResponseR\n" +
	"dimensions\x12-\n" +
	"\arequest\x18\n" +
	" \x01(\v2\x13.browser.TabRequestR\arequest*D\n" +
	"\vOrientation\x12\v\n" +
	"\aDefault\x10\x00\x12\a\n" +
	"\x03Top\x10\x01\x12\n" +
	"\n" +
	"\x06Bottom\x10\x02\x12\b\n" +
	"\x04Left\x10\x03\x12\t\n" +
	"\x05Right\x10\x042U\n" +
	"\x0eResourceOpener\x12C\n" +
	"\x04Open\x12\x1c.browser.OpenResourceRequest\x1a\x1d.browser.OpenResourceResponse2\x80\x02\n" +
	"\rNotifications\x129\n" +
	"\x06Notify\x12\x16.browser.NotifyRequest\x1a\x17.browser.NotifyResponse\x12=\n" +
	"\n" +
	"NotifyOnce\x12\x16.browser.NotifyRequest\x1a\x17.browser.NotifyResponse\x12u\n" +
	"\x1aUpdateNotificationProgress\x12*.browser.UpdateNotificationProgressRequest\x1a+.browser.UpdateNotificationProgressResponse2N\n" +
	"\x0eEventPublisher\x12<\n" +
	"\aPublish\x12\x17.browser.PublishRequest\x1a\x18.browser.PublishResponse2\xdf\x03\n" +
	"\rWindowManager\x126\n" +
	"\x05Focus\x12\x15.browser.FocusRequest\x1a\x16.browser.FocusResponse\x12B\n" +
	"\x05Split\x12\x1b.browser.SplitWindowMessage\x1a\x16.handler.ServerMessage\"\x00(\x010\x01\x128\n" +
	"\x03Bar\x12\x13.browser.BarMessage\x1a\x16.handler.ServerMessage\"\x00(\x010\x01\x12H\n" +
	"\bFloating\x12\x1e.browser.FloatingWindowMessage\x1a\x16.handler.ServerMessage\"\x00(\x010\x01\x126\n" +
	"\x03Tab\x12\x13.browser.TabMessage\x1a\x16.handler.ServerMessage(\x010\x01\x12L\n" +
	"\n" +
	"SetContent\x12 .browser.WindowSetContentMessage\x1a\x16.handler.ServerMessage\"\x00(\x010\x01\x12H\n" +
	"\vCloseWindow\x12\x1b.browser.WindowCloseRequest\x1a\x1c.browser.WindowCloseResponse2Q\n" +
	"\bFloating\x12E\n" +
	"\n" +
	"Dimensions\x12\x1a.browser.DimensionsRequest\x1a\x1b.browser.DimensionsResponseB@Z>github.com/unstablebuild/rune-go-sdk/api/browserapi/browserrpcb\x06proto3"

var (
	file_browserrpc_browser_proto_rawDescOnce sync.Once
	file_browserrpc_browser_proto_rawDescData []byte
)

func file_browserrpc_browser_proto_rawDescGZIP() []byte {
	file_browserrpc_browser_proto_rawDescOnce.Do(func() {
		file_browserrpc_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_browserrpc_browser_proto_rawDesc), len(file_browserrpc_browser_proto_rawDesc)))
	})
	return file_browserrpc_browser_proto_rawDescData
}

var file_browserrpc_browser_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_browserrpc_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_browserrpc_browser_proto_goTypes = []any{
	(Orientation)(0),                            // 0: browser.Orientation
	(BarRequest_Frame)(0),                       // 1: browser.BarRequest.Frame
	(*OpenResourceRequest)(nil),                 // 2: browser.OpenResourceRequest
	(*OpenResourceResponse)(nil),                // 3: browser.OpenResourceResponse
	(*NotifyRequest)(nil),                       // 4: browser.NotifyRequest
	(*NotifyResponse)(nil),                      // 5: browser.NotifyResponse
	(*UpdateNotificationProgressRequest)(nil),   // 6: browser.UpdateNotificationProgressRequest
	(*UpdateNotificationProgressResponse)(nil),  // 7: browser.UpdateNotificationProgressResponse
	(*Mapping)(nil),                             // 8: browser.Mapping
	(*SplitRequest)(nil),                        // 9: browser.SplitRequest
	(*BarRequest)(nil),                          // 10: browser.BarRequest
	(*FloatingWindowRequest)(nil),               // 11: browser.FloatingWindowRequest
	(*TabRequest)(nil),                          // 12: browser.TabRequest
	(*FocusRequest)(nil),                        // 13: browser.FocusRequest
	(*FocusResponse)(nil),                       // 14: browser.FocusResponse
	(*PublishRequest)(nil),                      // 15: browser.PublishRequest
	(*PublishResponse)(nil),                     // 16: browser.PublishResponse
	(*WindowCloseRequest)(nil),                  // 17: browser.WindowCloseRequest
	(*WindowCloseResponse)(nil),                 // 18: browser.WindowCloseResponse
	(*WindowSetContentRequest)(nil),             // 19: browser.WindowSetContentRequest
	(*DimensionsRequest)(nil),                   // 20: browser.DimensionsRequest
	(*DimensionsResponse)(nil),                  // 21: browser.DimensionsResponse
	(*FloatingWindowMessage)(nil),               // 22: browser.FloatingWindowMessage
	(*SplitWindowMessage)(nil),                  // 23: browser.SplitWindowMessage
	(*BarMessage)(nil),                          // 24: browser.BarMessage
	(*WindowSetContentMessage)(nil),             // 25: browser.WindowSetContentMessage
	(*TabMessage)(nil),                          // 26: browser.TabMessage
	(*termrpc.Event)(nil),                       // 27: term.Event
	(*termrpc.Coordinates)(nil),                 // 28: term.Coordinates
	(handlerrpc.MessageType)(0),                 // 29: handler.MessageType
	(*handlerrpc.DrawStreamResponse)(nil),       // 30: handler.DrawStreamResponse
	(*handlerrpc.HandleStreamResponse)(nil),     // 31: handler.HandleStreamResponse
	(*handlerrpc.CloseStreamResponse)(nil),      // 32: handler.CloseStreamResponse
	(*handlerrpc.CursorStreamResponse)(nil),     // 33: handler.CursorStreamResponse
	(*handlerrpc.SelectionStreamResponse)(nil),  // 34: handler.SelectionStreamResponse
	(*handlerrpc.DimensionsStreamResponse)(nil), // 35: handler.DimensionsStreamResponse
	(*handlerrpc.ServerMessage)(nil),            // 36: handler.ServerMessage
}
var file_browserrpc_browser_proto_depIdxs = []int32{
	27, // 0: browser.Mapping.from:type_name -> term.Event
	27, // 1: browser.Mapping.to:type_name -> term.Event
	0,  // 2: browser.SplitRequest.orientation:type_name -> browser.Orientation
	0,  // 3: browser.BarRequest.orientation:type_name -> browser.Orientation
	1,  // 4: browser.BarRequest.frame:type_name -> browser.BarRequest.Frame
	28, // 5: browser.FloatingWindowRequest.offset:type_name -> term.Coordinates
	27, // 6: browser.PublishRequest.ev:type_name -> term.Event
	29, // 7: browser.FloatingWindowMessage.type:type_name -> handler.MessageType
	30, // 8: browser.FloatingWindowMessage.draw:type_name -> handler.DrawStreamResponse
	31, // 9: browser.FloatingWindowMessage.handle:type_name -> handler.HandleStreamResponse
	32, // 10: browser.FloatingWindowMessage.close:type_name -> handler.CloseStreamResponse
	33, // 11: browser.FloatingWindowMessage.cursor:type_name -> handler.CursorStreamResponse
	34, // 12: browser.FloatingWindowMessage.selection:type_name -> handler.SelectionStreamResponse
	35, // 13: browser.FloatingWindowMessage.dimensions:type_name -> handler.DimensionsStreamResponse
	11, // 14: browser.FloatingWindowMessage.request:type_name -> browser.FloatingWindowRequest
	29, // 15: browser.SplitWindowMessage.type:type_name -> handler.MessageType
	30, // 16: browser.SplitWindowMessage.draw:type_name -> handler.DrawStreamResponse
	31, // 17: browser.SplitWindowMessage.handle:type_name -> handler.HandleStreamResponse
	32, // 18: browser.SplitWindowMessage.close:type_name -> handler.CloseStreamResponse
	33, // 19: browser.SplitWindowMessage.cursor:type_name -> handler.CursorStreamResponse
	34, // 20: browser.SplitWindowMessage.selection:type_name -> handler.SelectionStreamResponse
	35, // 21: browser.SplitWindowMessage.dimensions:type_name -> handler.DimensionsStreamResponse
	9,  // 22: browser.SplitWindowMessage.request:type_name -> browser.SplitRequest
	29, // 23: browser.BarMessage.type:type_name -> handler.MessageType
	30, // 24: browser.BarMessage.draw:type_name -> handler.DrawStreamResponse
	31, // 25: browser.BarMessage.handle:type_name -> handler.HandleStreamResponse
	32, // 26: browser.BarMessage.close:type_name -> handler.CloseStreamResponse
	33, // 27: browser.BarMessage.cursor:type_name -> handler.CursorStreamResponse
	34, // 28: browser.BarMessage.selection:type_name -> handler.SelectionStreamResponse
	35, // 29: browser.BarMessage.dimensions:type_name -> handler.DimensionsStreamResponse
	10, // 30: browser.BarMessage.request:type_name -> browser.BarRequest
	29, // 31: browser.WindowSetContentMessage.type:type_name -> handler.MessageType
	30, // 32: browser.WindowSetContentMessage.draw:type_name -> handler.DrawStreamResponse
	31, // 33: browser.WindowSetContentMessage.handle:type_name -> handler.HandleStreamResponse
	32, // 34: browser.WindowSetContentMessage.close:type_name -> handler.CloseStreamResponse
	33, // 35: browser.WindowSetContentMessage.cursor:type_name -> handler.CursorStreamResponse
	34, // 36: browser.WindowSetContentMessage.selection:type_name -> handler.SelectionStreamResponse
	35, // 37: browser.WindowSetContentMessage.dimensions:type_name -> handler.DimensionsStreamResponse
	19, // 38: browser.WindowSetContentMessage.request:type_name -> browser.WindowSetContentRequest
	29, // 39: browser.TabMessage.type:type_name -> handler.MessageType
	30, // 40: browser.TabMessage.draw:type_name -> handler.DrawStreamResponse
	31, // 41: browser.TabMessage.handle:type_name -> handler.HandleStreamResponse
	32, // 42: browser.TabMessage.close:type_name -> handler.CloseStreamResponse
	33, // 43: browser.TabMessage.cursor:type_name -> handler.CursorStreamResponse
	34, // 44: browser.TabMessage.selection:type_name -> handler.SelectionStreamResponse
	35, // 45: browser.TabMessage.dimensions:type_name -> handler.DimensionsStreamResponse
	12, // 46: browser.TabMessage.request:type_name -> browser.TabRequest
	2,  // 47: browser.ResourceOpener.Open:input_type -> browser.OpenResourceRequest
	4,  // 48: browser.Notifications.Notify:input_type -> browser.NotifyRequest
	4,  // 49: browser.Notifications.NotifyOnce:input_type -> browser.NotifyRequest
	6,  // 50: browser.Notifications.UpdateNotificationProgress:input_type -> browser.UpdateNotificationProgressRequest
	15, // 51: browser.EventPublisher.Publish:input_type -> browser.PublishRequest
	13, // 52: browser.WindowManager.Focus:input_type -> browser.FocusRequest
	23, // 53: browser.WindowManager.Split:input_type -> browser.SplitWindowMessage
	24, // 54: browser.WindowManager.Bar:input_type -> browser.BarMessage
	22, // 55: browser.WindowManager.Floating:input_type -> browser.FloatingWindowMessage
	26, // 56: browser.WindowManager.Tab:input_type -> browser.TabMessage
	25, // 57: browser.WindowManager.SetContent:input_type -> browser.WindowSetContentMessage
	17, // 58: browser.WindowManager.CloseWindow:input_type -> browser.WindowCloseRequest
	20, // 59: browser.Floating.Dimensions:input_type -> browser.DimensionsRequest
	3,  // 60: browser.ResourceOpener.Open:output_type -> browser.OpenResourceResponse
	5,  // 61: browser.Notifications.Notify:output_type -> browser.NotifyResponse
	5,  // 62: browser.Notifications.NotifyOnce:output_type -> browser.NotifyResponse
	7,  // 63: browser.Notifications.UpdateNotificationProgress:output_type -> browser.UpdateNotificationProgressResponse
	16, // 64: browser.EventPublisher.Publish:output_type -> browser.PublishResponse
	14, // 65: browser.WindowManager.Focus:output_type -> browser.FocusResponse
	36, // 66: browser.WindowManager.Split:output_type -> handler.ServerMessage
	36, // 67: browser.WindowManager.Bar:output_type -> handler.ServerMessage
	36, // 68: browser.WindowManager.Floating:output_type -> handler.ServerMessage
	36, // 69: browser.WindowManager.Tab:output_type -> handler.ServerMessage
	36, // 70: browser.WindowManager.SetContent:output_type -> handler.ServerMessage
	18, // 71: browser.WindowManager.CloseWindow:output_type -> browser.WindowCloseResponse
	21, // 72: browser.Floating.Dimensions:output_type -> browser.DimensionsResponse
	60, // [60:73] is the sub-list for method output_type
	47, // [47:60] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_browserrpc_browser_proto_init() }
func file_browserrpc_browser_proto_init() {
	if File_browserrpc_browser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_browserrpc_browser_proto_rawDesc), len(file_browserrpc_browser_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_browserrpc_browser_proto_goTypes,
		DependencyIndexes: file_browserrpc_browser_proto_depIdxs,
		EnumInfos:         file_browserrpc_browser_proto_enumTypes,
		MessageInfos:      file_browserrpc_browser_proto_msgTypes,
	}.Build()
	File_browserrpc_browser_proto = out.File
	file_browserrpc_browser_proto_goTypes = nil
	file_browserrpc_browser_proto_depIdxs = nil
}
