// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: textrpc/editor.proto

package textrpc

import (
	termrpc "github.com/unstablebuild/rune-go-sdk/term/termrpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EditorEvent_Type int32

const (
	EditorEvent_TypeOpen      EditorEvent_Type = 0
	EditorEvent_TypeClose     EditorEvent_Type = 1
	EditorEvent_TypeFlush     EditorEvent_Type = 2
	EditorEvent_TypeEdit      EditorEvent_Type = 3
	EditorEvent_TypeScroll    EditorEvent_Type = 5
	EditorEvent_TypeCreate    EditorEvent_Type = 12
	EditorEvent_TypeChange    EditorEvent_Type = 13
	EditorEvent_TypeFocus     EditorEvent_Type = 6
	EditorEvent_TypeUnfocus   EditorEvent_Type = 7
	EditorEvent_TypeCursor    EditorEvent_Type = 8
	EditorEvent_TypeSelection EditorEvent_Type = 9
	EditorEvent_TypeRename    EditorEvent_Type = 10
	EditorEvent_TypeRemove    EditorEvent_Type = 11
	EditorEvent_TypeHidden    EditorEvent_Type = 14
	EditorEvent_TypeVisible   EditorEvent_Type = 15
)

// Enum value maps for EditorEvent_Type.
var (
	EditorEvent_Type_name = map[int32]string{
		0:  "TypeOpen",
		1:  "TypeClose",
		2:  "TypeFlush",
		3:  "TypeEdit",
		5:  "TypeScroll",
		12: "TypeCreate",
		13: "TypeChange",
		6:  "TypeFocus",
		7:  "TypeUnfocus",
		8:  "TypeCursor",
		9:  "TypeSelection",
		10: "TypeRename",
		11: "TypeRemove",
		14: "TypeHidden",
		15: "TypeVisible",
	}
	EditorEvent_Type_value = map[string]int32{
		"TypeOpen":      0,
		"TypeClose":     1,
		"TypeFlush":     2,
		"TypeEdit":      3,
		"TypeScroll":    5,
		"TypeCreate":    12,
		"TypeChange":    13,
		"TypeFocus":     6,
		"TypeUnfocus":   7,
		"TypeCursor":    8,
		"TypeSelection": 9,
		"TypeRename":    10,
		"TypeRemove":    11,
		"TypeHidden":    14,
		"TypeVisible":   15,
	}
)

func (x EditorEvent_Type) Enum() *EditorEvent_Type {
	p := new(EditorEvent_Type)
	*p = x
	return p
}

func (x EditorEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EditorEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_textrpc_editor_proto_enumTypes[0].Descriptor()
}

func (EditorEvent_Type) Type() protoreflect.EnumType {
	return &file_textrpc_editor_proto_enumTypes[0]
}

func (x EditorEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EditorEvent_Type.Descriptor instead.
func (EditorEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{3, 0}
}

type URI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URI) Reset() {
	*x = URI{}
	mi := &file_textrpc_editor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URI) ProtoMessage() {}

func (x *URI) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URI.ProtoReflect.Descriptor instead.
func (*URI) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{0}
}

func (x *URI) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type EditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  *URI                   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Buffer        []*termrpc.CellRow     `protobuf:"bytes,2,rep,name=buffer,proto3" json:"buffer,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Recovered     bool                   `protobuf:"varint,4,opt,name=recovered,proto3" json:"recovered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditRequest) Reset() {
	*x = EditRequest{}
	mi := &file_textrpc_editor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRequest) ProtoMessage() {}

func (x *EditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRequest.ProtoReflect.Descriptor instead.
func (*EditRequest) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{1}
}

func (x *EditRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *EditRequest) GetBuffer() []*termrpc.CellRow {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *EditRequest) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *EditRequest) GetRecovered() bool {
	if x != nil {
		return x.Recovered
	}
	return false
}

type EditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditResponse) Reset() {
	*x = EditResponse{}
	mi := &file_textrpc_editor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditResponse) ProtoMessage() {}

func (x *EditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditResponse.ProtoReflect.Descriptor instead.
func (*EditResponse) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{2}
}

type EditorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EditorEvent_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=text.EditorEvent_Type" json:"type,omitempty"`
	ResourceName  *URI                   `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Start         *termrpc.Coordinates   `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End           *termrpc.Coordinates   `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	From          *termrpc.Coordinates   `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"`
	To            *termrpc.Coordinates   `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditorEvent) Reset() {
	*x = EditorEvent{}
	mi := &file_textrpc_editor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorEvent) ProtoMessage() {}

func (x *EditorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorEvent.ProtoReflect.Descriptor instead.
func (*EditorEvent) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{3}
}

func (x *EditorEvent) GetType() EditorEvent_Type {
	if x != nil {
		return x.Type
	}
	return EditorEvent_TypeOpen
}

func (x *EditorEvent) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *EditorEvent) GetStart() *termrpc.Coordinates {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *EditorEvent) GetEnd() *termrpc.Coordinates {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *EditorEvent) GetFrom() *termrpc.Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EditorEvent) GetTo() *termrpc.Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EditorEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SubscribeEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          []EditorEvent_Type     `protobuf:"varint,1,rep,packed,name=type,proto3,enum=text.EditorEvent_Type" json:"type,omitempty"`
	Unsubscribe   bool                   `protobuf:"varint,3,opt,name=unsubscribe,proto3" json:"unsubscribe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventRequest) Reset() {
	*x = SubscribeEventRequest{}
	mi := &file_textrpc_editor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventRequest) ProtoMessage() {}

func (x *SubscribeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventRequest) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeEventRequest) GetType() []EditorEvent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SubscribeEventRequest) GetUnsubscribe() bool {
	if x != nil {
		return x.Unsubscribe
	}
	return false
}

type SetLocationListRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	ResourceName  *URI                               `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ListId        string                             `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Locations     []*SetLocationListRequest_Location `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	Priority      uint32                             `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocationListRequest) Reset() {
	*x = SetLocationListRequest{}
	mi := &file_textrpc_editor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationListRequest) ProtoMessage() {}

func (x *SetLocationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationListRequest.ProtoReflect.Descriptor instead.
func (*SetLocationListRequest) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{5}
}

func (x *SetLocationListRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *SetLocationListRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *SetLocationListRequest) GetLocations() []*SetLocationListRequest_Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *SetLocationListRequest) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SetLocationListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocationListResponse) Reset() {
	*x = SetLocationListResponse{}
	mi := &file_textrpc_editor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationListResponse) ProtoMessage() {}

func (x *SetLocationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationListResponse.ProtoReflect.Descriptor instead.
func (*SetLocationListResponse) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{6}
}

type EditCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  *URI                   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Start         *termrpc.Coordinates   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *termrpc.Coordinates   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Str           string                 `protobuf:"bytes,4,opt,name=str,proto3" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCellRequest) Reset() {
	*x = EditCellRequest{}
	mi := &file_textrpc_editor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCellRequest) ProtoMessage() {}

func (x *EditCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCellRequest.ProtoReflect.Descriptor instead.
func (*EditCellRequest) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{7}
}

func (x *EditCellRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *EditCellRequest) GetStart() *termrpc.Coordinates {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *EditCellRequest) GetEnd() *termrpc.Coordinates {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *EditCellRequest) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type EditCellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *termrpc.Coordinates   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *termrpc.Coordinates   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Old           string                 `protobuf:"bytes,3,opt,name=old,proto3" json:"old,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCellResponse) Reset() {
	*x = EditCellResponse{}
	mi := &file_textrpc_editor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCellResponse) ProtoMessage() {}

func (x *EditCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCellResponse.ProtoReflect.Descriptor instead.
func (*EditCellResponse) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{8}
}

func (x *EditCellResponse) GetFrom() *termrpc.Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EditCellResponse) GetTo() *termrpc.Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EditCellResponse) GetOld() string {
	if x != nil {
		return x.Old
	}
	return ""
}

type RawCellsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  *URI                   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawCellsRequest) Reset() {
	*x = RawCellsRequest{}
	mi := &file_textrpc_editor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCellsRequest) ProtoMessage() {}

func (x *RawCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCellsRequest.ProtoReflect.Descriptor instead.
func (*RawCellsRequest) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{9}
}

func (x *RawCellsRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

type RawCellsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*termrpc.CellRow     `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawCellsResponse) Reset() {
	*x = RawCellsResponse{}
	mi := &file_textrpc_editor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawCellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCellsResponse) ProtoMessage() {}

func (x *RawCellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCellsResponse.ProtoReflect.Descriptor instead.
func (*RawCellsResponse) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{10}
}

func (x *RawCellsResponse) GetRows() []*termrpc.CellRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type MoveToLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  *URI                   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ListId        string                 `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToLocationRequest) Reset() {
	*x = MoveToLocationRequest{}
	mi := &file_textrpc_editor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToLocationRequest) ProtoMessage() {}

func (x *MoveToLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToLocationRequest.ProtoReflect.Descriptor instead.
func (*MoveToLocationRequest) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{11}
}

func (x *MoveToLocationRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *MoveToLocationRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

type MoveToLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToLocationResponse) Reset() {
	*x = MoveToLocationResponse{}
	mi := &file_textrpc_editor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToLocationResponse) ProtoMessage() {}

func (x *MoveToLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToLocationResponse.ProtoReflect.Descriptor instead.
func (*MoveToLocationResponse) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{12}
}

type SetCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *termrpc.Coordinates   `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	ResourceName  *URI                   `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCursorRequest) Reset() {
	*x = SetCursorRequest{}
	mi := &file_textrpc_editor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCursorRequest) ProtoMessage() {}

func (x *SetCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCursorRequest.ProtoReflect.Descriptor instead.
func (*SetCursorRequest) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{13}
}

func (x *SetCursorRequest) GetPos() *termrpc.Coordinates {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SetCursorRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

type SetCursorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCursorResponse) Reset() {
	*x = SetCursorResponse{}
	mi := &file_textrpc_editor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCursorResponse) ProtoMessage() {}

func (x *SetCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCursorResponse.ProtoReflect.Descriptor instead.
func (*SetCursorResponse) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{14}
}

type CursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  *URI                   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorRequest) Reset() {
	*x = CursorRequest{}
	mi := &file_textrpc_editor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorRequest) ProtoMessage() {}

func (x *CursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorRequest.ProtoReflect.Descriptor instead.
func (*CursorRequest) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{15}
}

func (x *CursorRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

type CursorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *termrpc.Coordinates   `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorResponse) Reset() {
	*x = CursorResponse{}
	mi := &file_textrpc_editor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorResponse) ProtoMessage() {}

func (x *CursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorResponse.ProtoReflect.Descriptor instead.
func (*CursorResponse) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{16}
}

func (x *CursorResponse) GetPos() *termrpc.Coordinates {
	if x != nil {
		return x.Pos
	}
	return nil
}

type EditorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  *URI                   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditorRequest) Reset() {
	*x = EditorRequest{}
	mi := &file_textrpc_editor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorRequest) ProtoMessage() {}

func (x *EditorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorRequest.ProtoReflect.Descriptor instead.
func (*EditorRequest) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{17}
}

func (x *EditorRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

type EditorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditorResponse) Reset() {
	*x = EditorResponse{}
	mi := &file_textrpc_editor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorResponse) ProtoMessage() {}

func (x *EditorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorResponse.ProtoReflect.Descriptor instead.
func (*EditorResponse) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{18}
}

type SetDefaultAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  *URI                   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Attributes    *termrpc.Attributes    `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultAttributesRequest) Reset() {
	*x = SetDefaultAttributesRequest{}
	mi := &file_textrpc_editor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultAttributesRequest) ProtoMessage() {}

func (x *SetDefaultAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultAttributesRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultAttributesRequest) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{19}
}

func (x *SetDefaultAttributesRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *SetDefaultAttributesRequest) GetAttributes() *termrpc.Attributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type SetDefaultAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultAttributesResponse) Reset() {
	*x = SetDefaultAttributesResponse{}
	mi := &file_textrpc_editor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultAttributesResponse) ProtoMessage() {}

func (x *SetDefaultAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultAttributesResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultAttributesResponse) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{20}
}

type SetLocationListRequest_Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *termrpc.Coordinates   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *termrpc.Coordinates   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Attr          *termrpc.Attributes    `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocationListRequest_Location) Reset() {
	*x = SetLocationListRequest_Location{}
	mi := &file_textrpc_editor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocationListRequest_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationListRequest_Location) ProtoMessage() {}

func (x *SetLocationListRequest_Location) ProtoReflect() protoreflect.Message {
	mi := &file_textrpc_editor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationListRequest_Location.ProtoReflect.Descriptor instead.
func (*SetLocationListRequest_Location) Descriptor() ([]byte, []int) {
	return file_textrpc_editor_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SetLocationListRequest_Location) GetFrom() *termrpc.Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SetLocationListRequest_Location) GetTo() *termrpc.Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SetLocationListRequest_Location) GetAttr() *termrpc.Attributes {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *SetLocationListRequest_Location) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SetLocationListRequest_Location) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

var File_textrpc_editor_proto protoreflect.FileDescriptor

const file_textrpc_editor_proto_rawDesc = "" +
	"\n" +
	"\x14textrpc/editor.proto\x12\x04text\x1a\x17term/termrpc/term.proto\"\x17\n" +
	"\x03URI\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"\x9f\x01\n" +
	"\vEditRequest\x12.\n" +
	"\rresource_name\x18\x01 \x01(\v2\t.text.URIR\fresourceName\x12%\n" +
	"\x06buffer\x18\x02 \x03(\v2\r.term.CellRowR\x06buffer\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\x12\x1c\n" +
	"\trecovered\x18\x04 \x01(\bR\trecovered\"\x0e\n" +
	"\fEditResponse\"\x92\x04\n" +
	"\vEditorEvent\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.text.EditorEvent.TypeR\x04type\x12.\n" +
	"\rresource_name\x18\x02 \x01(\v2\t.text.URIR\fresourceName\x12'\n" +
	"\x05start\x18\x04 \x01(\v2\x11.term.CoordinatesR\x05start\x12#\n" +
	"\x03end\x18\x05 \x01(\v2\x11.term.CoordinatesR\x03end\x12%\n" +
	"\x04from\x18\x06 \x01(\v2\x11.term.CoordinatesR\x04from\x12!\n" +
	"\x02to\x18\a \x01(\v2\x11.term.CoordinatesR\x02to\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\"\xf4\x01\n" +
	"\x04Type\x12\f\n" +
	"\bTypeOpen\x10\x00\x12\r\n" +
	"\tTypeClose\x10\x01\x12\r\n" +
	"\tTypeFlush\x10\x02\x12\f\n" +
	"\bTypeEdit\x10\x03\x12\x0e\n" +
	"\n" +
	"TypeScroll\x10\x05\x12\x0e\n" +
	"\n" +
	"TypeCreate\x10\f\x12\x0e\n" +
	"\n" +
	"TypeChange\x10\r\x12\r\n" +
	"\tTypeFocus\x10\x06\x12\x0f\n" +
	"\vTypeUnfocus\x10\a\x12\x0e\n" +
	"\n" +
	"TypeCursor\x10\b\x12\x11\n" +
	"\rTypeSelection\x10\t\x12\x0e\n" +
	"\n" +
	"TypeRename\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"TypeRemove\x10\v\x12\x0e\n" +
	"\n" +
	"TypeHidden\x10\x0e\x12\x0f\n" +
	"\vTypeVisible\x10\x0f\"e\n" +
	"\x15SubscribeEventRequest\x12*\n" +
	"\x04type\x18\x01 \x03(\x0e2\x16.text.EditorEvent.TypeR\x04type\x12 \n" +
	"\vunsubscribe\x18\x03 \x01(\bR\vunsubscribe\"\xe5\x02\n" +
	"\x16SetLocationListRequest\x12.\n" +
	"\rresource_name\x18\x01 \x01(\v2\t.text.URIR\fresourceName\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\tR\x06listId\x12C\n" +
	"\tlocations\x18\x03 \x03(\v2%.text.SetLocationListRequest.LocationR\tlocations\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\rR\bpriority\x1a\xa0\x01\n" +
	"\bLocation\x12%\n" +
	"\x04from\x18\x01 \x01(\v2\x11.term.CoordinatesR\x04from\x12!\n" +
	"\x02to\x18\x02 \x01(\v2\x11.term.CoordinatesR\x02to\x12$\n" +
	"\x04attr\x18\x03 \x01(\v2\x10.term.AttributesR\x04attr\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\"\x19\n" +
	"\x17SetLocationListResponse\"\xa1\x01\n" +
	"\x0fEditCellRequest\x12.\n" +
	"\rresource_name\x18\x01 \x01(\v2\t.text.URIR\fresourceName\x12'\n" +
	"\x05start\x18\x02 \x01(\v2\x11.term.CoordinatesR\x05start\x12#\n" +
	"\x03end\x18\x03 \x01(\v2\x11.term.CoordinatesR\x03end\x12\x10\n" +
	"\x03str\x18\x04 \x01(\tR\x03str\"n\n" +
	"\x10EditCellResponse\x12%\n" +
	"\x04from\x18\x01 \x01(\v2\x11.term.CoordinatesR\x04from\x12!\n" +
	"\x02to\x18\x02 \x01(\v2\x11.term.CoordinatesR\x02to\x12\x10\n" +
	"\x03old\x18\x03 \x01(\tR\x03old\"A\n" +
	"\x0fRawCellsRequest\x12.\n" +
	"\rresource_name\x18\x01 \x01(\v2\t.text.URIR\fresourceName\"5\n" +
	"\x10RawCellsResponse\x12!\n" +
	"\x04rows\x18\x01 \x03(\v2\r.term.CellRowR\x04rows\"`\n" +
	"\x15MoveToLocationRequest\x12.\n" +
	"\rresource_name\x18\x01 \x01(\v2\t.text.URIR\fresourceName\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\tR\x06listId\"\x18\n" +
	"\x16MoveToLocationResponse\"g\n" +
	"\x10SetCursorRequest\x12#\n" +
	"\x03pos\x18\x01 \x01(\v2\x11.term.CoordinatesR\x03pos\x12.\n" +
	"\rresource_name\x18\x02 \x01(\v2\t.text.URIR\fresourceName\"\x13\n" +
	"\x11SetCursorResponse\"?\n" +
	"\rCursorRequest\x12.\n" +
	"\rresource_name\x18\x01 \x01(\v2\t.text.URIR\fresourceName\"5\n" +
	"\x0eCursorResponse\x12#\n" +
	"\x03pos\x18\x01 \x01(\v2\x11.term.CoordinatesR\x03pos\"?\n" +
	"\rEditorRequest\x12.\n" +
	"\rresource_name\x18\x01 \x01(\v2\t.text.URIR\fresourceName\"\x10\n" +
	"\x0eEditorResponse\"\x7f\n" +
	"\x1bSetDefaultAttributesRequest\x12.\n" +
	"\rresource_name\x18\x01 \x01(\v2\t.text.URIR\fresourceName\x120\n" +
	"\n" +
	"attributes\x18\x02 \x01(\v2\x10.term.AttributesR\n" +
	"attributes\"\x1e\n" +
	"\x1cSetDefaultAttributesResponse2\xec\x05\n" +
	"\x06Editor\x12-\n" +
	"\x04Edit\x12\x11.text.EditRequest\x1a\x12.text.EditResponse\x12<\n" +
	"\tSetCursor\x12\x16.text.SetCursorRequest\x1a\x17.text.SetCursorResponse\x123\n" +
	"\x06Cursor\x12\x13.text.CursorRequest\x1a\x14.text.CursorResponse\x123\n" +
	"\x06Editor\x12\x13.text.EditorRequest\x1a\x14.text.EditorResponse\x12N\n" +
	"\x0fSetLocationList\x12\x1c.text.SetLocationListRequest\x1a\x1d.text.SetLocationListResponse\x12O\n" +
	"\x12MoveToNextLocation\x12\x1b.text.MoveToLocationRequest\x1a\x1c.text.MoveToLocationResponse\x12O\n" +
	"\x12MoveToPrevLocation\x12\x1b.text.MoveToLocationRequest\x1a\x1c.text.MoveToLocationResponse\x129\n" +
	"\bEditCell\x12\x15.text.EditCellRequest\x1a\x16.text.EditCellResponse\x129\n" +
	"\bRawCells\x12\x15.text.RawCellsRequest\x1a\x16.text.RawCellsResponse\x12]\n" +
	"\x14SetDefaultAttributes\x12!.text.SetDefaultAttributesRequest\x1a\".text.SetDefaultAttributesResponse\x12D\n" +
	"\x0eSubscribeEvent\x12\x1b.text.SubscribeEventRequest\x1a\x11.text.EditorEvent(\x010\x01B:Z8github.com/unstablebuild/rune-go-sdk/api/textapi/textrpcb\x06proto3"

var (
	file_textrpc_editor_proto_rawDescOnce sync.Once
	file_textrpc_editor_proto_rawDescData []byte
)

func file_textrpc_editor_proto_rawDescGZIP() []byte {
	file_textrpc_editor_proto_rawDescOnce.Do(func() {
		file_textrpc_editor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_textrpc_editor_proto_rawDesc), len(file_textrpc_editor_proto_rawDesc)))
	})
	return file_textrpc_editor_proto_rawDescData
}

var file_textrpc_editor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_textrpc_editor_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_textrpc_editor_proto_goTypes = []any{
	(EditorEvent_Type)(0),                   // 0: text.EditorEvent.Type
	(*URI)(nil),                             // 1: text.URI
	(*EditRequest)(nil),                     // 2: text.EditRequest
	(*EditResponse)(nil),                    // 3: text.EditResponse
	(*EditorEvent)(nil),                     // 4: text.EditorEvent
	(*SubscribeEventRequest)(nil),           // 5: text.SubscribeEventRequest
	(*SetLocationListRequest)(nil),          // 6: text.SetLocationListRequest
	(*SetLocationListResponse)(nil),         // 7: text.SetLocationListResponse
	(*EditCellRequest)(nil),                 // 8: text.EditCellRequest
	(*EditCellResponse)(nil),                // 9: text.EditCellResponse
	(*RawCellsRequest)(nil),                 // 10: text.RawCellsRequest
	(*RawCellsResponse)(nil),                // 11: text.RawCellsResponse
	(*MoveToLocationRequest)(nil),           // 12: text.MoveToLocationRequest
	(*MoveToLocationResponse)(nil),          // 13: text.MoveToLocationResponse
	(*SetCursorRequest)(nil),                // 14: text.SetCursorRequest
	(*SetCursorResponse)(nil),               // 15: text.SetCursorResponse
	(*CursorRequest)(nil),                   // 16: text.CursorRequest
	(*CursorResponse)(nil),                  // 17: text.CursorResponse
	(*EditorRequest)(nil),                   // 18: text.EditorRequest
	(*EditorResponse)(nil),                  // 19: text.EditorResponse
	(*SetDefaultAttributesRequest)(nil),     // 20: text.SetDefaultAttributesRequest
	(*SetDefaultAttributesResponse)(nil),    // 21: text.SetDefaultAttributesResponse
	(*SetLocationListRequest_Location)(nil), // 22: text.SetLocationListRequest.Location
	(*termrpc.CellRow)(nil),                 // 23: term.CellRow
	(*termrpc.Coordinates)(nil),             // 24: term.Coordinates
	(*termrpc.Attributes)(nil),              // 25: term.Attributes
}
var file_textrpc_editor_proto_depIdxs = []int32{
	1,  // 0: text.EditRequest.resource_name:type_name -> text.URI
	23, // 1: text.EditRequest.buffer:type_name -> term.CellRow
	0,  // 2: text.EditorEvent.type:type_name -> text.EditorEvent.Type
	1,  // 3: text.EditorEvent.resource_name:type_name -> text.URI
	24, // 4: text.EditorEvent.start:type_name -> term.Coordinates
	24, // 5: text.EditorEvent.end:type_name -> term.Coordinates
	24, // 6: text.EditorEvent.from:type_name -> term.Coordinates
	24, // 7: text.EditorEvent.to:type_name -> term.Coordinates
	0,  // 8: text.SubscribeEventRequest.type:type_name -> text.EditorEvent.Type
	1,  // 9: text.SetLocationListRequest.resource_name:type_name -> text.URI
	22, // 10: text.SetLocationListRequest.locations:type_name -> text.SetLocationListRequest.Location
	1,  // 11: text.EditCellRequest.resource_name:type_name -> text.URI
	24, // 12: text.EditCellRequest.start:type_name -> term.Coordinates
	24, // 13: text.EditCellRequest.end:type_name -> term.Coordinates
	24, // 14: text.EditCellResponse.from:type_name -> term.Coordinates
	24, // 15: text.EditCellResponse.to:type_name -> term.Coordinates
	1,  // 16: text.RawCellsRequest.resource_name:type_name -> text.URI
	23, // 17: text.RawCellsResponse.rows:type_name -> term.CellRow
	1,  // 18: text.MoveToLocationRequest.resource_name:type_name -> text.URI
	24, // 19: text.SetCursorRequest.pos:type_name -> term.Coordinates
	1,  // 20: text.SetCursorRequest.resource_name:type_name -> text.URI
	1,  // 21: text.CursorRequest.resource_name:type_name -> text.URI
	24, // 22: text.CursorResponse.pos:type_name -> term.Coordinates
	1,  // 23: text.EditorRequest.resource_name:type_name -> text.URI
	1,  // 24: text.SetDefaultAttributesRequest.resource_name:type_name -> text.URI
	25, // 25: text.SetDefaultAttributesRequest.attributes:type_name -> term.Attributes
	24, // 26: text.SetLocationListRequest.Location.from:type_name -> term.Coordinates
	24, // 27: text.SetLocationListRequest.Location.to:type_name -> term.Coordinates
	25, // 28: text.SetLocationListRequest.Location.attr:type_name -> term.Attributes
	2,  // 29: text.Editor.Edit:input_type -> text.EditRequest
	14, // 30: text.Editor.SetCursor:input_type -> text.SetCursorRequest
	16, // 31: text.Editor.Cursor:input_type -> text.CursorRequest
	18, // 32: text.Editor.Editor:input_type -> text.EditorRequest
	6,  // 33: text.Editor.SetLocationList:input_type -> text.SetLocationListRequest
	12, // 34: text.Editor.MoveToNextLocation:input_type -> text.MoveToLocationRequest
	12, // 35: text.Editor.MoveToPrevLocation:input_type -> text.MoveToLocationRequest
	8,  // 36: text.Editor.EditCell:input_type -> text.EditCellRequest
	10, // 37: text.Editor.RawCells:input_type -> text.RawCellsRequest
	20, // 38: text.Editor.SetDefaultAttributes:input_type -> text.SetDefaultAttributesRequest
	5,  // 39: text.Editor.SubscribeEvent:input_type -> text.SubscribeEventRequest
	3,  // 40: text.Editor.Edit:output_type -> text.EditResponse
	15, // 41: text.Editor.SetCursor:output_type -> text.SetCursorResponse
	17, // 42: text.Editor.Cursor:output_type -> text.CursorResponse
	19, // 43: text.Editor.Editor:output_type -> text.EditorResponse
	7,  // 44: text.Editor.SetLocationList:output_type -> text.SetLocationListResponse
	13, // 45: text.Editor.MoveToNextLocation:output_type -> text.MoveToLocationResponse
	13, // 46: text.Editor.MoveToPrevLocation:output_type -> text.MoveToLocationResponse
	9,  // 47: text.Editor.EditCell:output_type -> text.EditCellResponse
	11, // 48: text.Editor.RawCells:output_type -> text.RawCellsResponse
	21, // 49: text.Editor.SetDefaultAttributes:output_type -> text.SetDefaultAttributesResponse
	4,  // 50: text.Editor.SubscribeEvent:output_type -> text.EditorEvent
	40, // [40:51] is the sub-list for method output_type
	29, // [29:40] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_textrpc_editor_proto_init() }
func file_textrpc_editor_proto_init() {
	if File_textrpc_editor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_textrpc_editor_proto_rawDesc), len(file_textrpc_editor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_textrpc_editor_proto_goTypes,
		DependencyIndexes: file_textrpc_editor_proto_depIdxs,
		EnumInfos:         file_textrpc_editor_proto_enumTypes,
		MessageInfos:      file_textrpc_editor_proto_msgTypes,
	}.Build()
	File_textrpc_editor_proto = out.File
	file_textrpc_editor_proto_goTypes = nil
	file_textrpc_editor_proto_depIdxs = nil
}
