// Copyright 2026 Unstable Build, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: debugrpc/debug.proto

package debugrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DebugService_Initialize_FullMethodName             = "/debug.DebugService/Initialize"
	DebugService_Launch_FullMethodName                 = "/debug.DebugService/Launch"
	DebugService_Attach_FullMethodName                 = "/debug.DebugService/Attach"
	DebugService_ConfigurationDone_FullMethodName      = "/debug.DebugService/ConfigurationDone"
	DebugService_Disconnect_FullMethodName             = "/debug.DebugService/Disconnect"
	DebugService_Continue_FullMethodName               = "/debug.DebugService/Continue"
	DebugService_Pause_FullMethodName                  = "/debug.DebugService/Pause"
	DebugService_Next_FullMethodName                   = "/debug.DebugService/Next"
	DebugService_StepIn_FullMethodName                 = "/debug.DebugService/StepIn"
	DebugService_StepOut_FullMethodName                = "/debug.DebugService/StepOut"
	DebugService_SetBreakpoints_FullMethodName         = "/debug.DebugService/SetBreakpoints"
	DebugService_SetFunctionBreakpoints_FullMethodName = "/debug.DebugService/SetFunctionBreakpoints"
	DebugService_Threads_FullMethodName                = "/debug.DebugService/Threads"
	DebugService_StackTrace_FullMethodName             = "/debug.DebugService/StackTrace"
	DebugService_Scopes_FullMethodName                 = "/debug.DebugService/Scopes"
	DebugService_Variables_FullMethodName              = "/debug.DebugService/Variables"
	DebugService_Evaluate_FullMethodName               = "/debug.DebugService/Evaluate"
	DebugService_SetVariable_FullMethodName            = "/debug.DebugService/SetVariable"
	DebugService_ReadMemory_FullMethodName             = "/debug.DebugService/ReadMemory"
	DebugService_Disassemble_FullMethodName            = "/debug.DebugService/Disassemble"
	DebugService_SubscribeEvents_FullMethodName        = "/debug.DebugService/SubscribeEvents"
)

// DebugServiceClient is the client API for DebugService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DebugService provides debugging operations following the DAP shape.
type DebugServiceClient interface {
	// Session Management
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	Launch(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error)
	Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*AttachResponse, error)
	ConfigurationDone(ctx context.Context, in *ConfigurationDoneRequest, opts ...grpc.CallOption) (*ConfigurationDoneResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	// Execution Control
	Continue(ctx context.Context, in *ContinueRequest, opts ...grpc.CallOption) (*ContinueResponse, error)
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error)
	Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextResponse, error)
	StepIn(ctx context.Context, in *StepInRequest, opts ...grpc.CallOption) (*StepInResponse, error)
	StepOut(ctx context.Context, in *StepOutRequest, opts ...grpc.CallOption) (*StepOutResponse, error)
	// Breakpoints
	SetBreakpoints(ctx context.Context, in *SetBreakpointsRequest, opts ...grpc.CallOption) (*SetBreakpointsResponse, error)
	SetFunctionBreakpoints(ctx context.Context, in *SetFunctionBreakpointsRequest, opts ...grpc.CallOption) (*SetFunctionBreakpointsResponse, error)
	// State Inspection
	Threads(ctx context.Context, in *ThreadsRequest, opts ...grpc.CallOption) (*ThreadsResponse, error)
	StackTrace(ctx context.Context, in *StackTraceRequest, opts ...grpc.CallOption) (*StackTraceResponse, error)
	Scopes(ctx context.Context, in *ScopesRequest, opts ...grpc.CallOption) (*ScopesResponse, error)
	Variables(ctx context.Context, in *VariablesRequest, opts ...grpc.CallOption) (*VariablesResponse, error)
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*SetVariableResponse, error)
	// Memory & Disassembly
	ReadMemory(ctx context.Context, in *ReadMemoryRequest, opts ...grpc.CallOption) (*ReadMemoryResponse, error)
	Disassemble(ctx context.Context, in *DisassembleRequest, opts ...grpc.CallOption) (*DisassembleResponse, error)
	// Events - Server-side streaming
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type debugServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDebugServiceClient(cc grpc.ClientConnInterface) DebugServiceClient {
	return &debugServiceClient{cc}
}

func (c *debugServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, DebugService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Launch(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchResponse)
	err := c.cc.Invoke(ctx, DebugService_Launch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*AttachResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachResponse)
	err := c.cc.Invoke(ctx, DebugService_Attach_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) ConfigurationDone(ctx context.Context, in *ConfigurationDoneRequest, opts ...grpc.CallOption) (*ConfigurationDoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurationDoneResponse)
	err := c.cc.Invoke(ctx, DebugService_ConfigurationDone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, DebugService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Continue(ctx context.Context, in *ContinueRequest, opts ...grpc.CallOption) (*ContinueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContinueResponse)
	err := c.cc.Invoke(ctx, DebugService_Continue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseResponse)
	err := c.cc.Invoke(ctx, DebugService_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextResponse)
	err := c.cc.Invoke(ctx, DebugService_Next_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) StepIn(ctx context.Context, in *StepInRequest, opts ...grpc.CallOption) (*StepInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepInResponse)
	err := c.cc.Invoke(ctx, DebugService_StepIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) StepOut(ctx context.Context, in *StepOutRequest, opts ...grpc.CallOption) (*StepOutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepOutResponse)
	err := c.cc.Invoke(ctx, DebugService_StepOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) SetBreakpoints(ctx context.Context, in *SetBreakpointsRequest, opts ...grpc.CallOption) (*SetBreakpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBreakpointsResponse)
	err := c.cc.Invoke(ctx, DebugService_SetBreakpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) SetFunctionBreakpoints(ctx context.Context, in *SetFunctionBreakpointsRequest, opts ...grpc.CallOption) (*SetFunctionBreakpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFunctionBreakpointsResponse)
	err := c.cc.Invoke(ctx, DebugService_SetFunctionBreakpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Threads(ctx context.Context, in *ThreadsRequest, opts ...grpc.CallOption) (*ThreadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThreadsResponse)
	err := c.cc.Invoke(ctx, DebugService_Threads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) StackTrace(ctx context.Context, in *StackTraceRequest, opts ...grpc.CallOption) (*StackTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StackTraceResponse)
	err := c.cc.Invoke(ctx, DebugService_StackTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Scopes(ctx context.Context, in *ScopesRequest, opts ...grpc.CallOption) (*ScopesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScopesResponse)
	err := c.cc.Invoke(ctx, DebugService_Scopes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Variables(ctx context.Context, in *VariablesRequest, opts ...grpc.CallOption) (*VariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariablesResponse)
	err := c.cc.Invoke(ctx, DebugService_Variables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, DebugService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*SetVariableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVariableResponse)
	err := c.cc.Invoke(ctx, DebugService_SetVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) ReadMemory(ctx context.Context, in *ReadMemoryRequest, opts ...grpc.CallOption) (*ReadMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadMemoryResponse)
	err := c.cc.Invoke(ctx, DebugService_ReadMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) Disassemble(ctx context.Context, in *DisassembleRequest, opts ...grpc.CallOption) (*DisassembleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisassembleResponse)
	err := c.cc.Invoke(ctx, DebugService_Disassemble_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DebugService_ServiceDesc.Streams[0], DebugService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DebugService_SubscribeEventsClient = grpc.ServerStreamingClient[Event]

// DebugServiceServer is the server API for DebugService service.
// All implementations must embed UnimplementedDebugServiceServer
// for forward compatibility.
//
// DebugService provides debugging operations following the DAP shape.
type DebugServiceServer interface {
	// Session Management
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	Launch(context.Context, *LaunchRequest) (*LaunchResponse, error)
	Attach(context.Context, *AttachRequest) (*AttachResponse, error)
	ConfigurationDone(context.Context, *ConfigurationDoneRequest) (*ConfigurationDoneResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	// Execution Control
	Continue(context.Context, *ContinueRequest) (*ContinueResponse, error)
	Pause(context.Context, *PauseRequest) (*PauseResponse, error)
	Next(context.Context, *NextRequest) (*NextResponse, error)
	StepIn(context.Context, *StepInRequest) (*StepInResponse, error)
	StepOut(context.Context, *StepOutRequest) (*StepOutResponse, error)
	// Breakpoints
	SetBreakpoints(context.Context, *SetBreakpointsRequest) (*SetBreakpointsResponse, error)
	SetFunctionBreakpoints(context.Context, *SetFunctionBreakpointsRequest) (*SetFunctionBreakpointsResponse, error)
	// State Inspection
	Threads(context.Context, *ThreadsRequest) (*ThreadsResponse, error)
	StackTrace(context.Context, *StackTraceRequest) (*StackTraceResponse, error)
	Scopes(context.Context, *ScopesRequest) (*ScopesResponse, error)
	Variables(context.Context, *VariablesRequest) (*VariablesResponse, error)
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	SetVariable(context.Context, *SetVariableRequest) (*SetVariableResponse, error)
	// Memory & Disassembly
	ReadMemory(context.Context, *ReadMemoryRequest) (*ReadMemoryResponse, error)
	Disassemble(context.Context, *DisassembleRequest) (*DisassembleResponse, error)
	// Events - Server-side streaming
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedDebugServiceServer()
}

// UnimplementedDebugServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDebugServiceServer struct{}

func (UnimplementedDebugServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedDebugServiceServer) Launch(context.Context, *LaunchRequest) (*LaunchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Launch not implemented")
}
func (UnimplementedDebugServiceServer) Attach(context.Context, *AttachRequest) (*AttachResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedDebugServiceServer) ConfigurationDone(context.Context, *ConfigurationDoneRequest) (*ConfigurationDoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigurationDone not implemented")
}
func (UnimplementedDebugServiceServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedDebugServiceServer) Continue(context.Context, *ContinueRequest) (*ContinueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Continue not implemented")
}
func (UnimplementedDebugServiceServer) Pause(context.Context, *PauseRequest) (*PauseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedDebugServiceServer) Next(context.Context, *NextRequest) (*NextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedDebugServiceServer) StepIn(context.Context, *StepInRequest) (*StepInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StepIn not implemented")
}
func (UnimplementedDebugServiceServer) StepOut(context.Context, *StepOutRequest) (*StepOutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StepOut not implemented")
}
func (UnimplementedDebugServiceServer) SetBreakpoints(context.Context, *SetBreakpointsRequest) (*SetBreakpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBreakpoints not implemented")
}
func (UnimplementedDebugServiceServer) SetFunctionBreakpoints(context.Context, *SetFunctionBreakpointsRequest) (*SetFunctionBreakpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFunctionBreakpoints not implemented")
}
func (UnimplementedDebugServiceServer) Threads(context.Context, *ThreadsRequest) (*ThreadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Threads not implemented")
}
func (UnimplementedDebugServiceServer) StackTrace(context.Context, *StackTraceRequest) (*StackTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StackTrace not implemented")
}
func (UnimplementedDebugServiceServer) Scopes(context.Context, *ScopesRequest) (*ScopesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scopes not implemented")
}
func (UnimplementedDebugServiceServer) Variables(context.Context, *VariablesRequest) (*VariablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Variables not implemented")
}
func (UnimplementedDebugServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedDebugServiceServer) SetVariable(context.Context, *SetVariableRequest) (*SetVariableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVariable not implemented")
}
func (UnimplementedDebugServiceServer) ReadMemory(context.Context, *ReadMemoryRequest) (*ReadMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadMemory not implemented")
}
func (UnimplementedDebugServiceServer) Disassemble(context.Context, *DisassembleRequest) (*DisassembleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disassemble not implemented")
}
func (UnimplementedDebugServiceServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedDebugServiceServer) mustEmbedUnimplementedDebugServiceServer() {}
func (UnimplementedDebugServiceServer) testEmbeddedByValue()                      {}

// UnsafeDebugServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DebugServiceServer will
// result in compilation errors.
type UnsafeDebugServiceServer interface {
	mustEmbedUnimplementedDebugServiceServer()
}

func RegisterDebugServiceServer(s grpc.ServiceRegistrar, srv DebugServiceServer) {
	// If the following call panics, it indicates UnimplementedDebugServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DebugService_ServiceDesc, srv)
}

func _DebugService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Launch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Launch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Launch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Launch(ctx, req.(*LaunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Attach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Attach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Attach(ctx, req.(*AttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_ConfigurationDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).ConfigurationDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_ConfigurationDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).ConfigurationDone(ctx, req.(*ConfigurationDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Continue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Continue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Continue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Continue(ctx, req.(*ContinueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Next_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Next(ctx, req.(*NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_StepIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).StepIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_StepIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).StepIn(ctx, req.(*StepInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_StepOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).StepOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_StepOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).StepOut(ctx, req.(*StepOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_SetBreakpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBreakpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).SetBreakpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_SetBreakpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).SetBreakpoints(ctx, req.(*SetBreakpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_SetFunctionBreakpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFunctionBreakpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).SetFunctionBreakpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_SetFunctionBreakpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).SetFunctionBreakpoints(ctx, req.(*SetFunctionBreakpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Threads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Threads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Threads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Threads(ctx, req.(*ThreadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_StackTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).StackTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_StackTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).StackTrace(ctx, req.(*StackTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Scopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Scopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Scopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Scopes(ctx, req.(*ScopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Variables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Variables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Variables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Variables(ctx, req.(*VariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_SetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).SetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_SetVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).SetVariable(ctx, req.(*SetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_ReadMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).ReadMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_ReadMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).ReadMemory(ctx, req.(*ReadMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_Disassemble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisassembleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServiceServer).Disassemble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DebugService_Disassemble_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServiceServer).Disassemble(ctx, req.(*DisassembleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DebugServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DebugService_SubscribeEventsServer = grpc.ServerStreamingServer[Event]

// DebugService_ServiceDesc is the grpc.ServiceDesc for DebugService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DebugService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "debug.DebugService",
	HandlerType: (*DebugServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _DebugService_Initialize_Handler,
		},
		{
			MethodName: "Launch",
			Handler:    _DebugService_Launch_Handler,
		},
		{
			MethodName: "Attach",
			Handler:    _DebugService_Attach_Handler,
		},
		{
			MethodName: "ConfigurationDone",
			Handler:    _DebugService_ConfigurationDone_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _DebugService_Disconnect_Handler,
		},
		{
			MethodName: "Continue",
			Handler:    _DebugService_Continue_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _DebugService_Pause_Handler,
		},
		{
			MethodName: "Next",
			Handler:    _DebugService_Next_Handler,
		},
		{
			MethodName: "StepIn",
			Handler:    _DebugService_StepIn_Handler,
		},
		{
			MethodName: "StepOut",
			Handler:    _DebugService_StepOut_Handler,
		},
		{
			MethodName: "SetBreakpoints",
			Handler:    _DebugService_SetBreakpoints_Handler,
		},
		{
			MethodName: "SetFunctionBreakpoints",
			Handler:    _DebugService_SetFunctionBreakpoints_Handler,
		},
		{
			MethodName: "Threads",
			Handler:    _DebugService_Threads_Handler,
		},
		{
			MethodName: "StackTrace",
			Handler:    _DebugService_StackTrace_Handler,
		},
		{
			MethodName: "Scopes",
			Handler:    _DebugService_Scopes_Handler,
		},
		{
			MethodName: "Variables",
			Handler:    _DebugService_Variables_Handler,
		},
		{
			MethodName: "Evaluate",
			Handler:    _DebugService_Evaluate_Handler,
		},
		{
			MethodName: "SetVariable",
			Handler:    _DebugService_SetVariable_Handler,
		},
		{
			MethodName: "ReadMemory",
			Handler:    _DebugService_ReadMemory_Handler,
		},
		{
			MethodName: "Disassemble",
			Handler:    _DebugService_Disassemble_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _DebugService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "debugrpc/debug.proto",
}
