// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: termrpc/term.proto

package termrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event_Type int32

const (
	Event_TypeKey        Event_Type = 0
	Event_TypeNone       Event_Type = 1
	Event_TypeMouse      Event_Type = 2
	Event_TypeInterrupt  Event_Type = 3
	Event_TypePasteStart Event_Type = 4
	Event_TypePasteEnd   Event_Type = 5
	Event_TypeFocus      Event_Type = 6
	Event_TypeUnfocus    Event_Type = 7
	Event_TypeResize     Event_Type = 8
	Event_TypeError      Event_Type = 9
	Event_TypeRaw        Event_Type = 10
)

// Enum value maps for Event_Type.
var (
	Event_Type_name = map[int32]string{
		0:  "TypeKey",
		1:  "TypeNone",
		2:  "TypeMouse",
		3:  "TypeInterrupt",
		4:  "TypePasteStart",
		5:  "TypePasteEnd",
		6:  "TypeFocus",
		7:  "TypeUnfocus",
		8:  "TypeResize",
		9:  "TypeError",
		10: "TypeRaw",
	}
	Event_Type_value = map[string]int32{
		"TypeKey":        0,
		"TypeNone":       1,
		"TypeMouse":      2,
		"TypeInterrupt":  3,
		"TypePasteStart": 4,
		"TypePasteEnd":   5,
		"TypeFocus":      6,
		"TypeUnfocus":    7,
		"TypeResize":     8,
		"TypeError":      9,
		"TypeRaw":        10,
	}
)

func (x Event_Type) Enum() *Event_Type {
	p := new(Event_Type)
	*p = x
	return p
}

func (x Event_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_termrpc_term_proto_enumTypes[0].Descriptor()
}

func (Event_Type) Type() protoreflect.EnumType {
	return &file_termrpc_term_proto_enumTypes[0]
}

func (x Event_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Type.Descriptor instead.
func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return file_termrpc_term_proto_rawDescGZIP(), []int{3, 0}
}

type Event_Mod int32

const (
	Event_None          Event_Mod = 0
	Event_Alt           Event_Mod = 4
	Event_Shift         Event_Mod = 16
	Event_Meta          Event_Mod = 18
	Event_Ctrl          Event_Mod = 17
	Event_CtrlShift     Event_Mod = 145
	Event_CtrlAlt       Event_Mod = 146
	Event_CtrlMeta      Event_Mod = 147
	Event_CtrlShiftAlt  Event_Mod = 149
	Event_CtrlShiftMeta Event_Mod = 148
	Event_CtrlAltMeta   Event_Mod = 151
	Event_ShiftMeta     Event_Mod = 129
	Event_AltMeta       Event_Mod = 130
	Event_AltShiftMeta  Event_Mod = 131
	Event_AltShift      Event_Mod = 113
)

// Enum value maps for Event_Mod.
var (
	Event_Mod_name = map[int32]string{
		0:   "None",
		4:   "Alt",
		16:  "Shift",
		18:  "Meta",
		17:  "Ctrl",
		145: "CtrlShift",
		146: "CtrlAlt",
		147: "CtrlMeta",
		149: "CtrlShiftAlt",
		148: "CtrlShiftMeta",
		151: "CtrlAltMeta",
		129: "ShiftMeta",
		130: "AltMeta",
		131: "AltShiftMeta",
		113: "AltShift",
	}
	Event_Mod_value = map[string]int32{
		"None":          0,
		"Alt":           4,
		"Shift":         16,
		"Meta":          18,
		"Ctrl":          17,
		"CtrlShift":     145,
		"CtrlAlt":       146,
		"CtrlMeta":      147,
		"CtrlShiftAlt":  149,
		"CtrlShiftMeta": 148,
		"CtrlAltMeta":   151,
		"ShiftMeta":     129,
		"AltMeta":       130,
		"AltShiftMeta":  131,
		"AltShift":      113,
	}
)

func (x Event_Mod) Enum() *Event_Mod {
	p := new(Event_Mod)
	*p = x
	return p
}

func (x Event_Mod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Mod) Descriptor() protoreflect.EnumDescriptor {
	return file_termrpc_term_proto_enumTypes[1].Descriptor()
}

func (Event_Mod) Type() protoreflect.EnumType {
	return &file_termrpc_term_proto_enumTypes[1]
}

func (x Event_Mod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Mod.Descriptor instead.
func (Event_Mod) EnumDescriptor() ([]byte, []int) {
	return file_termrpc_term_proto_rawDescGZIP(), []int{3, 1}
}

type Event_Key int32

const (
	Event_Null           Event_Key = 0
	Event_F2             Event_Key = 1
	Event_F3             Event_Key = 2
	Event_F4             Event_Key = 3
	Event_F5             Event_Key = 4
	Event_F6             Event_Key = 5
	Event_F7             Event_Key = 6
	Event_F8             Event_Key = 7
	Event_F9             Event_Key = 8
	Event_F10            Event_Key = 9
	Event_F11            Event_Key = 10
	Event_F12            Event_Key = 11
	Event_Insert         Event_Key = 12
	Event_Delete         Event_Key = 13
	Event_Home           Event_Key = 14
	Event_End            Event_Key = 15
	Event_Pgup           Event_Key = 16
	Event_Pgdn           Event_Key = 17
	Event_ArrowUp        Event_Key = 18
	Event_ArrowDown      Event_Key = 19
	Event_ArrowLeft      Event_Key = 20
	Event_ArrowRight     Event_Key = 21
	Event_MouseLeft      Event_Key = 22
	Event_MouseMiddle    Event_Key = 23
	Event_MouseRight     Event_Key = 24
	Event_MouseRelease   Event_Key = 25
	Event_MouseWheelUp   Event_Key = 26
	Event_MouseWheelDown Event_Key = 27
	Event_F1             Event_Key = 28
	Event_Backspace      Event_Key = 38
	Event_Tab            Event_Key = 40
	Event_Enter          Event_Key = 45
	Event_Esc            Event_Key = 60
	Event_Space          Event_Key = 72 // Backspace2 = 73;
)

// Enum value maps for Event_Key.
var (
	Event_Key_name = map[int32]string{
		0:  "Null",
		1:  "F2",
		2:  "F3",
		3:  "F4",
		4:  "F5",
		5:  "F6",
		6:  "F7",
		7:  "F8",
		8:  "F9",
		9:  "F10",
		10: "F11",
		11: "F12",
		12: "Insert",
		13: "Delete",
		14: "Home",
		15: "End",
		16: "Pgup",
		17: "Pgdn",
		18: "ArrowUp",
		19: "ArrowDown",
		20: "ArrowLeft",
		21: "ArrowRight",
		22: "MouseLeft",
		23: "MouseMiddle",
		24: "MouseRight",
		25: "MouseRelease",
		26: "MouseWheelUp",
		27: "MouseWheelDown",
		28: "F1",
		38: "Backspace",
		40: "Tab",
		45: "Enter",
		60: "Esc",
		72: "Space",
	}
	Event_Key_value = map[string]int32{
		"Null":           0,
		"F2":             1,
		"F3":             2,
		"F4":             3,
		"F5":             4,
		"F6":             5,
		"F7":             6,
		"F8":             7,
		"F9":             8,
		"F10":            9,
		"F11":            10,
		"F12":            11,
		"Insert":         12,
		"Delete":         13,
		"Home":           14,
		"End":            15,
		"Pgup":           16,
		"Pgdn":           17,
		"ArrowUp":        18,
		"ArrowDown":      19,
		"ArrowLeft":      20,
		"ArrowRight":     21,
		"MouseLeft":      22,
		"MouseMiddle":    23,
		"MouseRight":     24,
		"MouseRelease":   25,
		"MouseWheelUp":   26,
		"MouseWheelDown": 27,
		"F1":             28,
		"Backspace":      38,
		"Tab":            40,
		"Enter":          45,
		"Esc":            60,
		"Space":          72,
	}
)

func (x Event_Key) Enum() *Event_Key {
	p := new(Event_Key)
	*p = x
	return p
}

func (x Event_Key) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Key) Descriptor() protoreflect.EnumDescriptor {
	return file_termrpc_term_proto_enumTypes[2].Descriptor()
}

func (Event_Key) Type() protoreflect.EnumType {
	return &file_termrpc_term_proto_enumTypes[2]
}

func (x Event_Key) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Key.Descriptor instead.
func (Event_Key) EnumDescriptor() ([]byte, []int) {
	return file_termrpc_term_proto_rawDescGZIP(), []int{3, 2}
}

type Attributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foreground    uint64                 `protobuf:"varint,2,opt,name=Foreground,proto3" json:"Foreground,omitempty"`
	Background    uint64                 `protobuf:"varint,3,opt,name=Background,proto3" json:"Background,omitempty"`
	Attrs         int64                  `protobuf:"varint,4,opt,name=Attrs,proto3" json:"Attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attributes) Reset() {
	*x = Attributes{}
	mi := &file_termrpc_term_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attributes) ProtoMessage() {}

func (x *Attributes) ProtoReflect() protoreflect.Message {
	mi := &file_termrpc_term_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attributes.ProtoReflect.Descriptor instead.
func (*Attributes) Descriptor() ([]byte, []int) {
	return file_termrpc_term_proto_rawDescGZIP(), []int{0}
}

func (x *Attributes) GetForeground() uint64 {
	if x != nil {
		return x.Foreground
	}
	return 0
}

func (x *Attributes) GetBackground() uint64 {
	if x != nil {
		return x.Background
	}
	return 0
}

func (x *Attributes) GetAttrs() int64 {
	if x != nil {
		return x.Attrs
	}
	return 0
}

type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     uint32                 `protobuf:"varint,1,opt,name=Character,proto3" json:"Character,omitempty"`
	Foreground    uint64                 `protobuf:"varint,2,opt,name=Foreground,proto3" json:"Foreground,omitempty"`
	Background    uint64                 `protobuf:"varint,3,opt,name=Background,proto3" json:"Background,omitempty"`
	Combining     []uint32               `protobuf:"varint,4,rep,packed,name=Combining,proto3" json:"Combining,omitempty"`
	Width         uint32                 `protobuf:"varint,5,opt,name=Width,proto3" json:"Width,omitempty"`
	Attrs         int64                  `protobuf:"varint,6,opt,name=Attrs,proto3" json:"Attrs,omitempty"`
	Bytes         uint32                 `protobuf:"varint,7,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_termrpc_term_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_termrpc_term_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_termrpc_term_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetCharacter() uint32 {
	if x != nil {
		return x.Character
	}
	return 0
}

func (x *Cell) GetForeground() uint64 {
	if x != nil {
		return x.Foreground
	}
	return 0
}

func (x *Cell) GetBackground() uint64 {
	if x != nil {
		return x.Background
	}
	return 0
}

func (x *Cell) GetCombining() []uint32 {
	if x != nil {
		return x.Combining
	}
	return nil
}

func (x *Cell) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Cell) GetAttrs() int64 {
	if x != nil {
		return x.Attrs
	}
	return 0
}

func (x *Cell) GetBytes() uint32 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type CellRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*Cell                `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellRow) Reset() {
	*x = CellRow{}
	mi := &file_termrpc_term_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellRow) ProtoMessage() {}

func (x *CellRow) ProtoReflect() protoreflect.Message {
	mi := &file_termrpc_term_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellRow.ProtoReflect.Descriptor instead.
func (*CellRow) Descriptor() ([]byte, []int) {
	return file_termrpc_term_proto_rawDescGZIP(), []int{2}
}

func (x *CellRow) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Event_Type             `protobuf:"varint,1,opt,name=type,proto3,enum=term.Event_Type" json:"type,omitempty"`
	Mod           Event_Mod              `protobuf:"varint,2,opt,name=mod,proto3,enum=term.Event_Mod" json:"mod,omitempty"`
	Key           Event_Key              `protobuf:"varint,3,opt,name=key,proto3,enum=term.Event_Key" json:"key,omitempty"`
	Char          uint32                 `protobuf:"varint,4,opt,name=Char,proto3" json:"Char,omitempty"`
	MouseX        int32                  `protobuf:"varint,5,opt,name=mouseX,proto3" json:"mouseX,omitempty"`
	MouseY        int32                  `protobuf:"varint,6,opt,name=mouseY,proto3" json:"mouseY,omitempty"`
	Raw           []byte                 `protobuf:"bytes,7,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_termrpc_term_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_termrpc_term_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_termrpc_term_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetType() Event_Type {
	if x != nil {
		return x.Type
	}
	return Event_TypeKey
}

func (x *Event) GetMod() Event_Mod {
	if x != nil {
		return x.Mod
	}
	return Event_None
}

func (x *Event) GetKey() Event_Key {
	if x != nil {
		return x.Key
	}
	return Event_Null
}

func (x *Event) GetChar() uint32 {
	if x != nil {
		return x.Char
	}
	return 0
}

func (x *Event) GetMouseX() int32 {
	if x != nil {
		return x.MouseX
	}
	return 0
}

func (x *Event) GetMouseY() int32 {
	if x != nil {
		return x.MouseY
	}
	return 0
}

func (x *Event) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Char          uint32                 `protobuf:"varint,3,opt,name=Char,proto3" json:"Char,omitempty"`
	Mod           Event_Mod              `protobuf:"varint,4,opt,name=mod,proto3,enum=term.Event_Mod" json:"mod,omitempty"`
	Key           Event_Key              `protobuf:"varint,5,opt,name=key,proto3,enum=term.Event_Key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_termrpc_term_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_termrpc_term_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_termrpc_term_proto_rawDescGZIP(), []int{4}
}

func (x *Key) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Key) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Key) GetChar() uint32 {
	if x != nil {
		return x.Char
	}
	return 0
}

func (x *Key) GetMod() Event_Mod {
	if x != nil {
		return x.Mod
	}
	return Event_None
}

func (x *Key) GetKey() Event_Key {
	if x != nil {
		return x.Key
	}
	return Event_Null
}

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_termrpc_term_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_termrpc_term_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_termrpc_term_proto_rawDescGZIP(), []int{5}
}

func (x *Coordinates) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinates) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_termrpc_term_proto protoreflect.FileDescriptor

const file_termrpc_term_proto_rawDesc = "" +
	"\n" +
	"\x12termrpc/term.proto\x12\x04term\"b\n" +
	"\n" +
	"Attributes\x12\x1e\n" +
	"\n" +
	"Foreground\x18\x02 \x01(\x04R\n" +
	"Foreground\x12\x1e\n" +
	"\n" +
	"Background\x18\x03 \x01(\x04R\n" +
	"Background\x12\x14\n" +
	"\x05Attrs\x18\x04 \x01(\x03R\x05Attrs\"\xc4\x01\n" +
	"\x04Cell\x12\x1c\n" +
	"\tCharacter\x18\x01 \x01(\rR\tCharacter\x12\x1e\n" +
	"\n" +
	"Foreground\x18\x02 \x01(\x04R\n" +
	"Foreground\x12\x1e\n" +
	"\n" +
	"Background\x18\x03 \x01(\x04R\n" +
	"Background\x12\x1c\n" +
	"\tCombining\x18\x04 \x03(\rR\tCombining\x12\x14\n" +
	"\x05Width\x18\x05 \x01(\rR\x05Width\x12\x14\n" +
	"\x05Attrs\x18\x06 \x01(\x03R\x05Attrs\x12\x14\n" +
	"\x05Bytes\x18\a \x01(\rR\x05Bytes\"+\n" +
	"\aCellRow\x12 \n" +
	"\x05cells\x18\x01 \x03(\v2\n" +
	".term.CellR\x05cells\"\xee\a\n" +
	"\x05Event\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.term.Event.TypeR\x04type\x12!\n" +
	"\x03mod\x18\x02 \x01(\x0e2\x0f.term.Event.ModR\x03mod\x12!\n" +
	"\x03key\x18\x03 \x01(\x0e2\x0f.term.Event.KeyR\x03key\x12\x12\n" +
	"\x04Char\x18\x04 \x01(\rR\x04Char\x12\x16\n" +
	"\x06mouseX\x18\x05 \x01(\x05R\x06mouseX\x12\x16\n" +
	"\x06mouseY\x18\x06 \x01(\x05R\x06mouseY\x12\x10\n" +
	"\x03raw\x18\a \x01(\fR\x03raw\"\xb5\x01\n" +
	"\x04Type\x12\v\n" +
	"\aTypeKey\x10\x00\x12\f\n" +
	"\bTypeNone\x10\x01\x12\r\n" +
	"\tTypeMouse\x10\x02\x12\x11\n" +
	"\rTypeInterrupt\x10\x03\x12\x12\n" +
	"\x0eTypePasteStart\x10\x04\x12\x10\n" +
	"\fTypePasteEnd\x10\x05\x12\r\n" +
	"\tTypeFocus\x10\x06\x12\x0f\n" +
	"\vTypeUnfocus\x10\a\x12\x0e\n" +
	"\n" +
	"TypeResize\x10\b\x12\r\n" +
	"\tTypeError\x10\t\x12\v\n" +
	"\aTypeRaw\x10\n" +
	"\"\xdc\x01\n" +
	"\x03Mod\x12\b\n" +
	"\x04None\x10\x00\x12\a\n" +
	"\x03Alt\x10\x04\x12\t\n" +
	"\x05Shift\x10\x10\x12\b\n" +
	"\x04Meta\x10\x12\x12\b\n" +
	"\x04Ctrl\x10\x11\x12\x0e\n" +
	"\tCtrlShift\x10\x91\x01\x12\f\n" +
	"\aCtrlAlt\x10\x92\x01\x12\r\n" +
	"\bCtrlMeta\x10\x93\x01\x12\x11\n" +
	"\fCtrlShiftAlt\x10\x95\x01\x12\x12\n" +
	"\rCtrlShiftMeta\x10\x94\x01\x12\x10\n" +
	"\vCtrlAltMeta\x10\x97\x01\x12\x0e\n" +
	"\tShiftMeta\x10\x81\x01\x12\f\n" +
	"\aAltMeta\x10\x82\x01\x12\x11\n" +
	"\fAltShiftMeta\x10\x83\x01\x12\f\n" +
	"\bAltShift\x10q\"\x8b\x03\n" +
	"\x03Key\x12\b\n" +
	"\x04Null\x10\x00\x12\x06\n" +
	"\x02F2\x10\x01\x12\x06\n" +
	"\x02F3\x10\x02\x12\x06\n" +
	"\x02F4\x10\x03\x12\x06\n" +
	"\x02F5\x10\x04\x12\x06\n" +
	"\x02F6\x10\x05\x12\x06\n" +
	"\x02F7\x10\x06\x12\x06\n" +
	"\x02F8\x10\a\x12\x06\n" +
	"\x02F9\x10\b\x12\a\n" +
	"\x03F10\x10\t\x12\a\n" +
	"\x03F11\x10\n" +
	"\x12\a\n" +
	"\x03F12\x10\v\x12\n" +
	"\n" +
	"\x06Insert\x10\f\x12\n" +
	"\n" +
	"\x06Delete\x10\r\x12\b\n" +
	"\x04Home\x10\x0e\x12\a\n" +
	"\x03End\x10\x0f\x12\b\n" +
	"\x04Pgup\x10\x10\x12\b\n" +
	"\x04Pgdn\x10\x11\x12\v\n" +
	"\aArrowUp\x10\x12\x12\r\n" +
	"\tArrowDown\x10\x13\x12\r\n" +
	"\tArrowLeft\x10\x14\x12\x0e\n" +
	"\n" +
	"ArrowRight\x10\x15\x12\r\n" +
	"\tMouseLeft\x10\x16\x12\x0f\n" +
	"\vMouseMiddle\x10\x17\x12\x0e\n" +
	"\n" +
	"MouseRight\x10\x18\x12\x10\n" +
	"\fMouseRelease\x10\x19\x12\x10\n" +
	"\fMouseWheelUp\x10\x1a\x12\x12\n" +
	"\x0eMouseWheelDown\x10\x1b\x12\x06\n" +
	"\x02F1\x10\x1c\x12\r\n" +
	"\tBackspace\x10&\x12\a\n" +
	"\x03Tab\x10(\x12\t\n" +
	"\x05Enter\x10-\x12\a\n" +
	"\x03Esc\x10<\x12\t\n" +
	"\x05Space\x10H\"\x91\x01\n" +
	"\x03Key\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04Char\x18\x03 \x01(\rR\x04Char\x12!\n" +
	"\x03mod\x18\x04 \x01(\x0e2\x0f.term.Event.ModR\x03mod\x12!\n" +
	"\x03key\x18\x05 \x01(\x0e2\x0f.term.Event.KeyR\x03key\")\n" +
	"\vCoordinates\x12\f\n" +
	"\x01X\x18\x01 \x01(\x05R\x01X\x12\f\n" +
	"\x01Y\x18\x02 \x01(\x05R\x01YB3Z1github.com/unstablebuild/rune-go-sdk/term/termrpcb\x06proto3"

var (
	file_termrpc_term_proto_rawDescOnce sync.Once
	file_termrpc_term_proto_rawDescData []byte
)

func file_termrpc_term_proto_rawDescGZIP() []byte {
	file_termrpc_term_proto_rawDescOnce.Do(func() {
		file_termrpc_term_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_termrpc_term_proto_rawDesc), len(file_termrpc_term_proto_rawDesc)))
	})
	return file_termrpc_term_proto_rawDescData
}

var file_termrpc_term_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_termrpc_term_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_termrpc_term_proto_goTypes = []any{
	(Event_Type)(0),     // 0: term.Event.Type
	(Event_Mod)(0),      // 1: term.Event.Mod
	(Event_Key)(0),      // 2: term.Event.Key
	(*Attributes)(nil),  // 3: term.Attributes
	(*Cell)(nil),        // 4: term.Cell
	(*CellRow)(nil),     // 5: term.CellRow
	(*Event)(nil),       // 6: term.Event
	(*Key)(nil),         // 7: term.Key
	(*Coordinates)(nil), // 8: term.Coordinates
}
var file_termrpc_term_proto_depIdxs = []int32{
	4, // 0: term.CellRow.cells:type_name -> term.Cell
	0, // 1: term.Event.type:type_name -> term.Event.Type
	1, // 2: term.Event.mod:type_name -> term.Event.Mod
	2, // 3: term.Event.key:type_name -> term.Event.Key
	1, // 4: term.Key.mod:type_name -> term.Event.Mod
	2, // 5: term.Key.key:type_name -> term.Event.Key
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_termrpc_term_proto_init() }
func file_termrpc_term_proto_init() {
	if File_termrpc_term_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_termrpc_term_proto_rawDesc), len(file_termrpc_term_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_termrpc_term_proto_goTypes,
		DependencyIndexes: file_termrpc_term_proto_depIdxs,
		EnumInfos:         file_termrpc_term_proto_enumTypes,
		MessageInfos:      file_termrpc_term_proto_msgTypes,
	}.Build()
	File_termrpc_term_proto = out.File
	file_termrpc_term_proto_goTypes = nil
	file_termrpc_term_proto_depIdxs = nil
}
